// Generated by Haxe 4.1.5
package hscript;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ErrorDef extends haxe.lang.ParamEnum
{
	public ErrorDef(int index, java.lang.Object[] params)
	{
		//line 240 "/usr/local/lib/haxe/std/java/internal/HxObject.hx"
		super(index, params);
	}
	
	
	public static final java.lang.String[] __hx_constructs = new java.lang.String[]{"EInvalidChar", "EUnexpected", "EUnterminatedString", "EUnterminatedComment", "EInvalidPreprocessor", "EUnknownVariable", "EInvalidIterator", "EInvalidOp", "EInvalidAccess", "ECustom"};
	
	public static hscript.ErrorDef EInvalidChar(int c)
	{
		//line 110 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(0, new java.lang.Object[]{c});
	}
	
	
	public static hscript.ErrorDef EUnexpected(java.lang.String s)
	{
		//line 111 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(1, new java.lang.Object[]{s});
	}
	
	
	public static final hscript.ErrorDef EUnterminatedString = new hscript.ErrorDef(2, null);
	
	public static final hscript.ErrorDef EUnterminatedComment = new hscript.ErrorDef(3, null);
	
	public static hscript.ErrorDef EInvalidPreprocessor(java.lang.String msg)
	{
		//line 114 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(4, new java.lang.Object[]{msg});
	}
	
	
	public static hscript.ErrorDef EUnknownVariable(java.lang.String v)
	{
		//line 115 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(5, new java.lang.Object[]{v});
	}
	
	
	public static hscript.ErrorDef EInvalidIterator(java.lang.String v)
	{
		//line 116 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(6, new java.lang.Object[]{v});
	}
	
	
	public static hscript.ErrorDef EInvalidOp(java.lang.String op)
	{
		//line 117 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(7, new java.lang.Object[]{op});
	}
	
	
	public static hscript.ErrorDef EInvalidAccess(java.lang.String f)
	{
		//line 118 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(8, new java.lang.Object[]{f});
	}
	
	
	public static hscript.ErrorDef ECustom(java.lang.String msg)
	{
		//line 119 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ErrorDef(9, new java.lang.Object[]{msg});
	}
	
	
	@Override public java.lang.String getTag()
	{
		//line 106 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return hscript.ErrorDef.__hx_constructs[this.index];
	}
	
	
}


