// Generated by Haxe 4.1.5
package hscript;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ExprDef extends haxe.lang.ParamEnum
{
	public ExprDef(int index, java.lang.Object[] params)
	{
		//line 240 "/usr/local/lib/haxe/std/java/internal/HxObject.hx"
		super(index, params);
	}
	
	
	public static final java.lang.String[] __hx_constructs = new java.lang.String[]{"EConst", "EIdent", "EVar", "EParent", "EBlock", "EField", "EBinop", "EUnop", "ECall", "EIf", "EWhile", "EFor", "EBreak", "EContinue", "EFunction", "EReturn", "EArray", "EArrayDecl", "ENew", "EThrow", "ETry", "EObject", "ETernary", "ESwitch", "EDoWhile", "EMeta", "ECheckType"};
	
	public static hscript.ExprDef EConst(hscript.Const c)
	{
		//line 46 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(0, new java.lang.Object[]{c});
	}
	
	
	public static hscript.ExprDef EIdent(java.lang.String v)
	{
		//line 47 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(1, new java.lang.Object[]{v});
	}
	
	
	public static hscript.ExprDef EVar(java.lang.String n, hscript.CType t, java.lang.Object e)
	{
		//line 48 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(2, new java.lang.Object[]{n, t, e});
	}
	
	
	public static hscript.ExprDef EParent(java.lang.Object e)
	{
		//line 49 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(3, new java.lang.Object[]{e});
	}
	
	
	public static hscript.ExprDef EBlock(haxe.root.Array<java.lang.Object> e)
	{
		//line 50 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(4, new java.lang.Object[]{e});
	}
	
	
	public static hscript.ExprDef EField(java.lang.Object e, java.lang.String f)
	{
		//line 51 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(5, new java.lang.Object[]{e, f});
	}
	
	
	public static hscript.ExprDef EBinop(java.lang.String op, java.lang.Object e1, java.lang.Object e2)
	{
		//line 52 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(6, new java.lang.Object[]{op, e1, e2});
	}
	
	
	public static hscript.ExprDef EUnop(java.lang.String op, boolean prefix, java.lang.Object e)
	{
		//line 53 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(7, new java.lang.Object[]{op, prefix, e});
	}
	
	
	public static hscript.ExprDef ECall(java.lang.Object e, haxe.root.Array<java.lang.Object> params)
	{
		//line 54 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(8, new java.lang.Object[]{e, params});
	}
	
	
	public static hscript.ExprDef EIf(java.lang.Object cond, java.lang.Object e1, java.lang.Object e2)
	{
		//line 55 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(9, new java.lang.Object[]{cond, e1, e2});
	}
	
	
	public static hscript.ExprDef EWhile(java.lang.Object cond, java.lang.Object e)
	{
		//line 56 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(10, new java.lang.Object[]{cond, e});
	}
	
	
	public static hscript.ExprDef EFor(java.lang.String v, java.lang.Object it, java.lang.Object e)
	{
		//line 57 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(11, new java.lang.Object[]{v, it, e});
	}
	
	
	public static final hscript.ExprDef EBreak = new hscript.ExprDef(12, null);
	
	public static final hscript.ExprDef EContinue = new hscript.ExprDef(13, null);
	
	public static hscript.ExprDef EFunction(haxe.root.Array<java.lang.Object> args, java.lang.Object e, java.lang.String name, hscript.CType ret)
	{
		//line 60 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(14, new java.lang.Object[]{args, e, name, ret});
	}
	
	
	public static hscript.ExprDef EReturn(java.lang.Object e)
	{
		//line 61 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(15, new java.lang.Object[]{e});
	}
	
	
	public static hscript.ExprDef EArray(java.lang.Object e, java.lang.Object index)
	{
		//line 62 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(16, new java.lang.Object[]{e, index});
	}
	
	
	public static hscript.ExprDef EArrayDecl(haxe.root.Array<java.lang.Object> e)
	{
		//line 63 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(17, new java.lang.Object[]{e});
	}
	
	
	public static hscript.ExprDef ENew(java.lang.String cl, haxe.root.Array<java.lang.Object> params)
	{
		//line 64 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(18, new java.lang.Object[]{cl, params});
	}
	
	
	public static hscript.ExprDef EThrow(java.lang.Object e)
	{
		//line 65 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(19, new java.lang.Object[]{e});
	}
	
	
	public static hscript.ExprDef ETry(java.lang.Object e, java.lang.String v, hscript.CType t, java.lang.Object ecatch)
	{
		//line 66 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(20, new java.lang.Object[]{e, v, t, ecatch});
	}
	
	
	public static hscript.ExprDef EObject(haxe.root.Array<java.lang.Object> fl)
	{
		//line 67 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(21, new java.lang.Object[]{fl});
	}
	
	
	public static hscript.ExprDef ETernary(java.lang.Object cond, java.lang.Object e1, java.lang.Object e2)
	{
		//line 68 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(22, new java.lang.Object[]{cond, e1, e2});
	}
	
	
	public static hscript.ExprDef ESwitch(java.lang.Object e, haxe.root.Array<java.lang.Object> cases, java.lang.Object defaultExpr)
	{
		//line 69 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(23, new java.lang.Object[]{e, cases, defaultExpr});
	}
	
	
	public static hscript.ExprDef EDoWhile(java.lang.Object cond, java.lang.Object e)
	{
		//line 70 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(24, new java.lang.Object[]{cond, e});
	}
	
	
	public static hscript.ExprDef EMeta(java.lang.String name, haxe.root.Array<java.lang.Object> args, java.lang.Object e)
	{
		//line 71 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(25, new java.lang.Object[]{name, args, e});
	}
	
	
	public static hscript.ExprDef ECheckType(java.lang.Object e, hscript.CType t)
	{
		//line 72 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.ExprDef(26, new java.lang.Object[]{e, t});
	}
	
	
	@Override public java.lang.String getTag()
	{
		//line 41 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return hscript.ExprDef.__hx_constructs[this.index];
	}
	
	
}


