// Generated by Haxe 4.1.5
package hscript;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class FieldKind extends haxe.lang.ParamEnum
{
	public FieldKind(int index, java.lang.Object[] params)
	{
		//line 240 "/usr/local/lib/haxe/std/java/internal/HxObject.hx"
		super(index, params);
	}
	
	
	public static final java.lang.String[] __hx_constructs = new java.lang.String[]{"KFunction", "KVar"};
	
	public static hscript.FieldKind KFunction(java.lang.Object f)
	{
		//line 165 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.FieldKind(0, new java.lang.Object[]{f});
	}
	
	
	public static hscript.FieldKind KVar(java.lang.Object v)
	{
		//line 166 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return new hscript.FieldKind(1, new java.lang.Object[]{v});
	}
	
	
	@Override public java.lang.String getTag()
	{
		//line 164 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Expr.hx"
		return hscript.FieldKind.__hx_constructs[this.index];
	}
	
	
}


