// Generated by Haxe 4.1.5
package hscript;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Interp_initOps_118__Fun extends haxe.lang.Function
{
	public Interp_initOps_118__Fun()
	{
		//line 118 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Interp.hx"
		super(2, 0);
	}
	
	
	public static hscript.Interp_initOps_118__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke2_o(double __fn_float1, java.lang.Object __fn_dyn1, double __fn_float2, java.lang.Object __fn_dyn2)
	{
		//line 118 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Interp.hx"
		java.lang.Object v2 = ( (( __fn_dyn2 == haxe.lang.Runtime.undefined )) ? (((java.lang.Object) (__fn_float2) )) : (((java.lang.Object) (__fn_dyn2) )) );
		//line 118 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Interp.hx"
		java.lang.Object v1 = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((java.lang.Object) (__fn_float1) )) : (((java.lang.Object) (__fn_dyn1) )) );
		//line 118 "/usr/local/lib/haxe/lib/hscript/2,4,0/hscript/Interp.hx"
		return ((java.lang.Object) (haxe.lang.Runtime.plus(v1, v2)) );
	}
	
	
}


