// Generated by Haxe 4.1.5
package ub1.server.dom;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HtmlNode extends haxe.lang.HxObject
{
	static
	{
		//line 4 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		ub1.server.dom.HtmlNode.ELEMENT_NODE = 1;
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		ub1.server.dom.HtmlNode.TEXT_NODE = 2;
		//line 6 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		ub1.server.dom.HtmlNode.COMMENT_NODE = 3;
	}
	
	public HtmlNode(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public HtmlNode(ub1.server.dom.HtmlElement parent, int type, int i1, int i2, int origin)
	{
		//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		ub1.server.dom.HtmlNode.__hx_ctor_ub1_server_dom_HtmlNode(this, parent, type, i1, i2, origin);
	}
	
	
	protected static void __hx_ctor_ub1_server_dom_HtmlNode(ub1.server.dom.HtmlNode __hx_this, ub1.server.dom.HtmlElement parent, int type, int i1, int i2, int origin)
	{
		//line 14 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		if (( parent != null )) 
		{
			//line 14 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			parent.addChild(__hx_this, null);
		}
		
		//line 15 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		__hx_this.type = type;
		//line 16 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		__hx_this.i1 = i1;
		//line 17 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		__hx_this.i2 = i2;
		//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		__hx_this.origin = origin;
	}
	
	
	public static int ELEMENT_NODE;
	
	public static int TEXT_NODE;
	
	public static int COMMENT_NODE;
	
	public ub1.server.dom.HtmlElement parent;
	
	public int type;
	
	public int i1;
	
	public int i2;
	
	public int origin;
	
	public ub1.server.dom.HtmlNode remove()
	{
		//line 22 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		if (( this.parent != null )) 
		{
			//line 23 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			this.parent.children.remove(this);
			//line 24 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			this.parent = null;
		}
		
		//line 26 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		return this;
	}
	
	
	@Override public java.lang.String toString()
	{
		//line 30 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		haxe.root.StringBuf sb = new haxe.root.StringBuf();
		//line 31 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		this.output(sb);
		//line 32 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		return sb.toString();
	}
	
	
	public haxe.root.StringBuf output(haxe.root.StringBuf sb)
	{
		//line 36 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		return sb;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				switch (field.hashCode())
				{
					case -1008619738:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("origin")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.origin = ((int) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3575610:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("type")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.type = ((int) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3305:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i2")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.i2 = ((int) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3304:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i1")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.i1 = ((int) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				switch (field.hashCode())
				{
					case -1008619738:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("origin")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.origin = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case -995424086:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("parent")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.parent = ((ub1.server.dom.HtmlElement) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3305:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i2")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.i2 = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3575610:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("type")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.type = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3304:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i1")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							this.i1 = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				switch (field.hashCode())
				{
					case -1005512447:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("output")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "output")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case -995424086:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("parent")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.parent;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case -1776922004:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("toString")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "toString")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3575610:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("type")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.type;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case -934610812:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("remove")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "remove")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3304:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i1")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.i1;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case -1008619738:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("origin")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.origin;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3305:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i2")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.i2;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				switch (field.hashCode())
				{
					case -1008619738:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("origin")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return ((double) (this.origin) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3575610:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("type")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return ((double) (this.type) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3305:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i2")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return ((double) (this.i2) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case 3304:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("i1")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return ((double) (this.i1) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				switch (field.hashCode())
				{
					case -1005512447:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("output")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.output(((haxe.root.StringBuf) (dynargs[0]) ));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case -934610812:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("remove")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.remove();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
					case -1776922004:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						if (field.equals("toString")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
							return this.toString();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		baseArr.push("origin");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		baseArr.push("i2");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		baseArr.push("i1");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		baseArr.push("type");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		baseArr.push("parent");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlNode.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


