// Generated by Haxe 4.1.5
package ub1.server.dom;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HtmlText extends ub1.server.dom.HtmlNode
{
	public HtmlText(haxe.lang.EmptyObject empty)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public HtmlText(ub1.server.dom.HtmlElement parent, java.lang.String text, int i1, int i2, int origin, java.lang.Object escape)
	{
		//line 10 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 10 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		ub1.server.dom.HtmlText.__hx_ctor_ub1_server_dom_HtmlText(this, parent, text, i1, i2, origin, escape);
	}
	
	
	protected static void __hx_ctor_ub1_server_dom_HtmlText(ub1.server.dom.HtmlText __hx_this, ub1.server.dom.HtmlElement parent, java.lang.String text, int i1, int i2, int origin, java.lang.Object escape)
	{
		//line 9 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		boolean escape1 = ( (haxe.lang.Runtime.eq(escape, null)) ? (true) : (haxe.lang.Runtime.toBool(((java.lang.Boolean) (escape) ))) );
		//line 10 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		ub1.server.dom.HtmlNode.__hx_ctor_ub1_server_dom_HtmlNode(__hx_this, parent, 2, i1, i2, origin);
		//line 11 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		__hx_this.escape = escape1;
		//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		__hx_this.text = ( (escape1) ? (haxe.root.StringTools.htmlUnescape(text)) : (text) );
	}
	
	
	public boolean escape;
	
	public java.lang.String text;
	
	@Override public haxe.root.StringBuf output(haxe.root.StringBuf sb)
	{
		//line 16 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		sb.add(haxe.lang.Runtime.toString(( (( this.text != null )) ? (( (this.escape) ? (haxe.root.StringTools.htmlEscape(this.text, null)) : (this.text) )) : ("") )));
		//line 16 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
		//line 17 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		return sb;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		{
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
			if (( field != null )) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
				switch (field.hashCode())
				{
					case 3556653:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						if (field.equals("text")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							this.text = haxe.lang.Runtime.toString(value);
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							return value;
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						break;
					}
					
					
					case -1294172031:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						if (field.equals("escape")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							this.escape = haxe.lang.Runtime.toBool(((java.lang.Boolean) (value) ));
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							return value;
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		{
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
			if (( field != null )) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
				switch (field.hashCode())
				{
					case -1005512447:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						if (field.equals("output")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "output")) );
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						break;
					}
					
					
					case -1294172031:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						if (field.equals("escape")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							return this.escape;
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						break;
					}
					
					
					case 3556653:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						if (field.equals("text")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
							return this.text;
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		baseArr.push("text");
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		baseArr.push("escape");
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlText.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


