// Generated by Haxe 4.1.5
package ub1.server.dom;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HtmlComment extends ub1.server.dom.HtmlNode
{
	public HtmlComment(haxe.lang.EmptyObject empty)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public HtmlComment(ub1.server.dom.HtmlElement parent, java.lang.String text, int i1, int i2, int origin)
	{
		//line 9 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 9 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		ub1.server.dom.HtmlComment.__hx_ctor_ub1_server_dom_HtmlComment(this, parent, text, i1, i2, origin);
	}
	
	
	protected static void __hx_ctor_ub1_server_dom_HtmlComment(ub1.server.dom.HtmlComment __hx_this, ub1.server.dom.HtmlElement parent, java.lang.String text, int i1, int i2, int origin)
	{
		//line 9 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		ub1.server.dom.HtmlNode.__hx_ctor_ub1_server_dom_HtmlNode(__hx_this, parent, 3, i1, i2, origin);
		//line 10 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		__hx_this.text = text;
	}
	
	
	public java.lang.String text;
	
	@Override public haxe.root.StringBuf output(haxe.root.StringBuf sb)
	{
		//line 14 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		sb.add(haxe.lang.Runtime.toString(( (( this.text != null )) ? (this.text) : ("") )));
		//line 14 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
		//line 15 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		return sb;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		{
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
			if (( field != null )) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
				switch (field.hashCode())
				{
					case 3556653:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
						if (field.equals("text")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
							this.text = haxe.lang.Runtime.toString(value);
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
							return value;
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		{
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
			boolean __temp_executeDef1 = true;
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
			if (( field != null )) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
				switch (field.hashCode())
				{
					case -1005512447:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
						if (field.equals("output")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "output")) );
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
						break;
					}
					
					
					case 3556653:
					{
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
						if (field.equals("text")) 
						{
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
							__temp_executeDef1 = false;
							//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
							return this.text;
						}
						
						//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
			if (__temp_executeDef1) 
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		baseArr.push("text");
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/dom/HtmlComment.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


