// Generated by Haxe 4.1.5
package utest;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Assert_Anon_743__Fun extends haxe.lang.Function
{
	public Assert_Anon_743__Fun()
	{
		//line 743 "/usr/local/lib/haxe/lib/utest/1,13,2/src/utest/Assert.hx"
		super(1, 0);
	}
	
	
	public static utest.Assert_Anon_743__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 743 "/usr/local/lib/haxe/lib/utest/1,13,2/src/utest/Assert.hx"
		java.lang.Object e = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((java.lang.Object) (__fn_float1) )) : (((java.lang.Object) (__fn_dyn1) )) );
		//line 743 "/usr/local/lib/haxe/lib/utest/1,13,2/src/utest/Assert.hx"
		return null;
	}
	
	
}


