// Generated by Haxe 4.1.5
package utest;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Assert_sameAs_349__Fun extends haxe.lang.Function
{
	public Assert_sameAs_349__Fun(java.lang.Object expected)
	{
		//line 349 "/usr/local/lib/haxe/lib/utest/1,13,2/src/utest/Assert.hx"
		super(0, 0);
		//line 349 "/usr/local/lib/haxe/lib/utest/1,13,2/src/utest/Assert.hx"
		this.expected = expected;
	}
	
	
	@Override public java.lang.Object __hx_invoke0_o()
	{
		//line 349 "/usr/local/lib/haxe/lib/utest/1,13,2/src/utest/Assert.hx"
		return this.expected;
	}
	
	
	public java.lang.Object expected;
	
}


