// Generated by Haxe 4.1.5
package ub1.core;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Element extends ub1.reactivity.ReScope
{
	static
	{
		//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.DOMATTR_PREFIX = "a_";
		//line 39 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.CLASSATTR_PREFIX = "c_";
		//line 40 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.CLASSATTR_PREFIXLEN = 2;
		//line 41 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.STYLEATTR_PREFIX = "s_";
		//line 42 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.STYLEATTR_PREFIXLEN = 2;
		//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.EVENTATTR_PREFIX = "ev_";
		//line 44 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.EVENTATTR_PREFIXLEN = 3;
		//line 45 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.HANDLERATTR_PREFIX = "on_";
		//line 46 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.HANDLERATTR_PREFIXLEN = 3;
		//line 47 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.ID_ATTR = "data-id";
		//line 48 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.CLONE_ATTR = "data-clone";
		//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.TEXT_PREFIX = "-tn";
		//line 227 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.DATA_VALUE = "data";
		//line 228 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.DATAOFFSET_VALUE = "dataOffset";
		//line 229 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.DATALENGTH_VALUE = "dataLength";
	}
	
	public Element(haxe.lang.EmptyObject empty)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public Element(ub1.core.Element parent, java.lang.Object props)
	{
		//line 60 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 60 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element.__hx_ctor_ub1_core_Element(this, parent, props);
	}
	
	
	protected static void __hx_ctor_ub1_core_Element(ub1.core.Element __hx_this, ub1.core.Element parent, java.lang.Object props)
	{
		//line 60 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.reactivity.ReScope.__hx_ctor_ub1_reactivity_ReScope(__hx_this, parent, ( (( ! (( haxe.lang.Runtime.getField(props, "clone", true) == null )) )) ? (null) : (haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(props, "name", true))) ), null, null, null);
		//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		__hx_this.id = ( (( ! (haxe.lang.Runtime.eq(haxe.lang.Runtime.getField(props, "id", true), null)) )) ? (((int) (haxe.lang.Runtime.toInt(haxe.lang.Runtime.getField(props, "id", true))) )) : (((ub1.core.Page) (__hx_this.baseRoot) ).registerElement(props)) );
		//line 62 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		__hx_this.dom = ((ub1.server.dom.HtmlElement) (haxe.lang.Runtime.getField(props, "dom", true)) );
		//line 63 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.PropertyTools.set(props, "dom", null);
		//line 64 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		__hx_this.clone = haxe.lang.Runtime.getField(props, "clone", true);
		//line 65 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.PropertyTools.set(props, "clone", null);
		//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			int _g = 0;
			//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			java.lang.Object props1 = haxe.lang.Runtime.getField(props, "attr", true);
			//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			haxe.root.Array<java.lang.String> _g1 = ( (( ! (( props1 == null )) )) ? (haxe.root.Reflect.fields(props1)) : (new haxe.root.Array<java.lang.String>(new java.lang.String[]{})) );
			//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			while (( _g < _g1.length ))
			{
				//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.String k = _g1.__get(_g);
				//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				 ++ _g;
				//line 67 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				ub1.reactivity.ReValue value = new ub1.reactivity.ReValue(__hx_this, ( "a_" + k ), ub1.lib.PropertyTools.get(haxe.lang.Runtime.getField(props, "attr", true), k, null), null, null, null, null);
				//line 68 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				value.userData = k;
				//line 69 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				value.callback = ((haxe.lang.Function) (new haxe.lang.Closure(__hx_this, "attrCallback")) );
			}
			
		}
		
		//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			int _g2 = 0;
			//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			java.lang.Object props2 = haxe.lang.Runtime.getField(props, "values", true);
			//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			haxe.root.Array<java.lang.String> _g3 = ( (( ! (( props2 == null )) )) ? (haxe.root.Reflect.fields(props2)) : (new haxe.root.Array<java.lang.String>(new java.lang.String[]{})) );
			//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			while (( _g2 < _g3.length ))
			{
				//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.String k1 = _g3.__get(_g2);
				//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				 ++ _g2;
				//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.String v = haxe.lang.Runtime.toString(ub1.lib.PropertyTools.get(haxe.lang.Runtime.getField(props, "values", true), k1, null));
				//line 73 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if (((java.lang.String) (((java.lang.Object) (k1) )) ).startsWith(haxe.lang.Runtime.toString("ev_"))) 
				{
					//line 74 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					if (ub1.reactivity.ReParser.isDynamic(v)) 
					{
						//line 75 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						__hx_this.addEventHandler(k1, v);
					}
					
				}
				else
				{
					//line 77 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					if (((java.lang.String) (((java.lang.Object) (k1) )) ).startsWith(haxe.lang.Runtime.toString("on_"))) 
					{
						//line 78 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (ub1.reactivity.ReParser.isDynamic(v)) 
						{
							//line 79 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__hx_this.addValueHandler(k1, v);
						}
						
					}
					else
					{
						//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						ub1.reactivity.ReValue value1 = new ub1.reactivity.ReValue(__hx_this, k1, v, null, null, null, null);
						//line 83 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (((java.lang.String) (((java.lang.Object) (k1) )) ).startsWith(haxe.lang.Runtime.toString("c_"))) 
						{
							//line 85 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							if (haxe.lang.Runtime.valEq(v, "")) 
							{
								//line 85 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
								value1.v = ((java.lang.Object) (true) );
							}
							
							//line 86 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							value1.userData = ub1.lib.Util.makeHyphenName(haxe.lang.StringExt.substr(k1, 2, null));
							//line 87 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							value1.callback = ((haxe.lang.Function) (new haxe.lang.Closure(__hx_this, "classCallback")) );
						}
						else
						{
							//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							if (((java.lang.String) (((java.lang.Object) (k1) )) ).startsWith(haxe.lang.Runtime.toString("s_"))) 
							{
								//line 89 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
								value1.userData = ub1.lib.Util.makeHyphenName(haxe.lang.StringExt.substr(k1, 2, null));
								//line 90 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
								value1.callback = ((haxe.lang.Function) (new haxe.lang.Closure(__hx_this, "styleCallback")) );
							}
							
						}
						
					}
					
				}
				
			}
			
		}
		
		//line 94 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (( ((haxe.root.Array<java.lang.Object>) (haxe.lang.Runtime.getField(props, "texts", true)) ) != null )) 
		{
			//line 95 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			int _g4 = 0;
			//line 95 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			haxe.root.Array<java.lang.Object> _g5 = ((haxe.root.Array<java.lang.Object>) (haxe.lang.Runtime.getField(props, "texts", true)) );
			//line 95 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			while (( _g4 < _g5.length ))
			{
				//line 95 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.Object t = _g5.__get(_g4);
				//line 95 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				 ++ _g4;
				//line 96 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				ub1.reactivity.ReValue value2 = new ub1.reactivity.ReValue(__hx_this, ( "-tn" + ((int) (haxe.lang.Runtime.getField_f(t, "index", true)) ) ), haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(t, "text", true)), null, null, null, null);
				//line 97 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				value2.userData = ub1.lib.DomTools.domGetNthChild(__hx_this.dom, ((int) (haxe.lang.Runtime.getField_f(t, "index", true)) ));
				//line 98 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				value2.callback = ((haxe.lang.Function) (new haxe.lang.Closure(__hx_this, "textCallback")) );
			}
			
		}
		
		//line 101 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.DomTools.domSet(__hx_this.dom, "data-id", ( "" + __hx_this.id ));
		//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (((haxe.ds.StringMap<ub1.reactivity.ReValue>) (((haxe.IMap<java.lang.String, ub1.reactivity.ReValue>) (__hx_this.values) )) ).exists("data")) 
		{
			//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			((ub1.reactivity.ReValue) (((haxe.ds.StringMap<ub1.reactivity.ReValue>) (((haxe.IMap<java.lang.String, ub1.reactivity.ReValue>) (__hx_this.values) )) ).get("data")) ).callback = ((haxe.lang.Function) (new haxe.lang.Closure(__hx_this, "dataCallback")) );
		}
		
		//line 103 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element __temp_expr1 = ((ub1.core.Element) (haxe.lang.Runtime.setField(props, "_e", __hx_this)) );
		//line 104 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (( ! (( haxe.lang.Runtime.getField(props, "_v", true) == null )) )) 
		{
			//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			int _g6 = 0;
			//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			java.lang.Object props3 = haxe.lang.Runtime.getField(props, "_v", true);
			//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			haxe.root.Array<java.lang.String> _g7 = ( (( ! (( props3 == null )) )) ? (haxe.root.Reflect.fields(props3)) : (new haxe.root.Array<java.lang.String>(new java.lang.String[]{})) );
			//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			while (( _g6 < _g7.length ))
			{
				//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.String k2 = _g7.__get(_g6);
				//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				 ++ _g6;
				//line 106 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				ub1.reactivity.ReValue value3 = ((ub1.reactivity.ReValue) (((haxe.ds.StringMap<ub1.reactivity.ReValue>) (((haxe.IMap<java.lang.String, ub1.reactivity.ReValue>) (__hx_this.values) )) ).get(k2)) );
				//line 107 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if (( value3 != null )) 
				{
					//line 107 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					value3.v = ub1.lib.PropertyTools.get(haxe.lang.Runtime.getField(props, "_v", true), k2, null);
				}
				
			}
			
		}
		
	}
	
	
	public static java.lang.String DOMATTR_PREFIX;
	
	public static java.lang.String CLASSATTR_PREFIX;
	
	public static int CLASSATTR_PREFIXLEN;
	
	public static java.lang.String STYLEATTR_PREFIX;
	
	public static int STYLEATTR_PREFIXLEN;
	
	public static java.lang.String EVENTATTR_PREFIX;
	
	public static int EVENTATTR_PREFIXLEN;
	
	public static java.lang.String HANDLERATTR_PREFIX;
	
	public static int HANDLERATTR_PREFIXLEN;
	
	public static java.lang.String ID_ATTR;
	
	public static java.lang.String CLONE_ATTR;
	
	public static java.lang.String TEXT_PREFIX;
	
	public static java.lang.String DATA_VALUE;
	
	public static java.lang.String DATAOFFSET_VALUE;
	
	public static java.lang.String DATALENGTH_VALUE;
	
	public ub1.core.Page root;
	
	public final ub1.core.Page get_root()
	{
		//line 52 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return ((ub1.core.Page) (this.baseRoot) );
	}
	
	
	public ub1.core.Element parent;
	
	public final ub1.core.Element get_parent()
	{
		//line 54 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return ((ub1.core.Element) (this.baseParent) );
	}
	
	
	public int id;
	
	public ub1.server.dom.HtmlElement dom;
	
	public java.lang.Object clone;
	
	public void addEventHandler(java.lang.String k, java.lang.Object v)
	{
		//line 117 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		java.lang.String type = haxe.lang.StringExt.substr(k, 3, null);
		//line 118 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.reactivity.ReValue value = new ub1.reactivity.ReValue(this, k, null, haxe.lang.Runtime.toString(v), false, false, null);
	}
	
	
	public void addValueHandler(java.lang.String k, java.lang.Object v)
	{
		//line 129 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		java.lang.String name = haxe.lang.StringExt.substr(k, 3, null);
		//line 130 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		new ub1.reactivity.ReValue(this, null, ( ( "[[" + name ) + "]]" ), haxe.lang.Runtime.toString(v), null, null, null);
	}
	
	
	public java.lang.Object attrCallback(java.lang.Object v, java.lang.String k, java.lang.String attrName)
	{
		//line 138 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.DomTools.domSet(this.dom, attrName, haxe.lang.Runtime.toString(v));
		//line 139 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return v;
	}
	
	
	public java.lang.Object textCallback(java.lang.Object v, java.lang.String k, ub1.server.dom.HtmlText n)
	{
		//line 143 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.DomTools.domSetNodeText(n, v);
		//line 144 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return v;
	}
	
	
	public java.lang.Object classCallback(java.lang.Object v, java.lang.String k, java.lang.String className)
	{
		//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		java.lang.String s = ub1.lib.DomTools.domGet(this.dom, "class");
		//line 156 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (( s == null )) 
		{
			//line 156 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			s = "";
		}
		
		//line 157 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		haxe.root.Array<java.lang.String> classes = new haxe.root.EReg("\\s+", "g").split(s);
		//line 158 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		boolean didChange = false;
		//line 159 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if ( ! ((( ( ( v == null ) || haxe.lang.Runtime.eq(v, false) ) || haxe.lang.Runtime.eq(v, "false") ))) ) 
		{
			//line 160 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( classes.indexOf(className, null) < 0 )) 
			{
				//line 161 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				classes.push(className);
				//line 162 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				didChange = true;
			}
			
		}
		else
		{
			//line 165 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			didChange = classes.remove(className);
		}
		
		//line 167 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (didChange) 
		{
			//line 168 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			java.lang.String v1 = ((java.lang.String) (((java.lang.Object) (classes.join(" ")) )) ).trim();
			//line 169 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			ub1.lib.DomTools.domSet(this.dom, "class", ( ( ! (haxe.lang.Runtime.valEq(v1, "")) ) ? (v1) : (null) ));
		}
		
		//line 172 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return v;
	}
	
	
	public java.lang.Object styleCallback(java.lang.Object v, java.lang.String k, java.lang.String styleName)
	{
		//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		java.lang.String s = ub1.lib.DomTools.domGet(this.dom, "style");
		//line 184 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (( s == null )) 
		{
			//line 184 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			s = "";
		}
		
		//line 185 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		haxe.root.Array<java.lang.String> styles = new haxe.root.EReg("\\s*;\\s*", "g").split(s);
		//line 186 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (( ( styles.length == 1 ) && haxe.lang.Runtime.valEq(styles.__get(0), "") )) 
		{
			//line 187 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			java.lang.String __temp_expr1 = haxe.lang.Runtime.toString(styles.pop());
		}
		
		//line 189 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		boolean didChange = false;
		//line 190 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		int ret = -1;
		//line 190 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		int i = 0;
		//line 191 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 191 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			int _g = 0;
			//line 191 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			while (( _g < styles.length ))
			{
				//line 191 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.String s1 = styles.__get(_g);
				//line 191 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				 ++ _g;
				//line 192 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				haxe.root.Array<java.lang.String> p = new haxe.root.EReg("\\s*:\\s*", "").split(s1);
				//line 193 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if (haxe.lang.Runtime.valEq(p.__get(0), styleName)) 
				{
					//line 194 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					ret = i;
					//line 195 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					break;
				}
				
				//line 197 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				 ++ i;
			}
			
		}
		
		//line 199 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (( ret < 0 )) 
		{
			//line 200 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( ! (( v == null )) )) 
			{
				//line 201 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				styles.push(( ( styleName + ":" ) + haxe.root.Std.string(v) ));
				//line 202 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				didChange = true;
			}
			
		}
		else
		{
			//line 205 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if ( ! ((( ( ( v == null ) || haxe.lang.Runtime.eq(v, false) ) || haxe.lang.Runtime.eq(v, "false") ))) ) 
			{
				//line 206 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.String s2 = ( ( styleName + ":" ) + haxe.root.Std.string(v) );
				//line 207 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if ( ! (haxe.lang.Runtime.valEq(styles.__get(ret), s2)) ) 
				{
					//line 208 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					styles.__set(ret, s2);
					//line 209 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					didChange = true;
				}
				
			}
			else
			{
				//line 212 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				styles.spliceVoid(ret, 1);
				//line 213 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				didChange = true;
			}
			
		}
		
		//line 216 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (didChange) 
		{
			//line 217 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			java.lang.String v1 = ( (( styles.length > 0 )) ? (styles.join(";")) : (null) );
			//line 218 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			ub1.lib.DomTools.domSet(this.dom, "style", v1);
		}
		
		//line 221 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return v;
	}
	
	
	public haxe.root.Array<ub1.core.Element> clones;
	
	public final void setClones(haxe.root.Array<ub1.core.Element> clones)
	{
		//line 233 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		this.clones = clones;
	}
	
	
	public final void initData()
	{
		//line 237 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (((haxe.ds.StringMap<ub1.reactivity.ReValue>) (((haxe.IMap<java.lang.String, ub1.reactivity.ReValue>) (this.values) )) ).exists("data")) 
		{
			//line 238 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			((ub1.reactivity.ReValue) (((haxe.ds.StringMap<ub1.reactivity.ReValue>) (((haxe.IMap<java.lang.String, ub1.reactivity.ReValue>) (this.values) )) ).get("data")) ).callback = ((haxe.lang.Function) (new haxe.lang.Closure(this, "dataCallback")) );
		}
		
	}
	
	
	public java.lang.Object dataCallback(java.lang.Object v, java.lang.String k, java.lang.Object userData)
	{
		//line 244 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		java.lang.Object offset = this.getLocal("dataOffset", null);
		//line 245 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		java.lang.Object length = this.getLocal("dataLength", null);
		//line 247 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		if (haxe.root.Std.isOfType(v, ((java.lang.Object) (haxe.root.Array.class) ))) 
		{
			//line 248 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			haxe.root.Array a = ((haxe.root.Array) (v) );
			//line 250 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( ( ! (haxe.lang.Runtime.eq(offset, null)) ) || ( ! (haxe.lang.Runtime.eq(length, null)) ) )) 
			{
				//line 251 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if (haxe.lang.Runtime.eq(offset, null)) 
				{
					//line 251 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					offset = 0;
				}
				
				//line 252 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if (haxe.lang.Runtime.eq(length, null)) 
				{
					//line 252 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					length = ((java.lang.Object) (java.lang.Math.max(((double) (0) ), ((double) (( ((int) (a.length) ) - ((int) (haxe.lang.Runtime.toInt(offset)) ) )) ))) );
				}
				
				//line 253 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				a = a.slice(((int) (haxe.lang.Runtime.toInt(offset)) ), ( ((int) (haxe.lang.Runtime.toInt(offset)) ) + ((int) (haxe.lang.Runtime.toInt(length)) ) ));
			}
			
			//line 256 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( ! (( this.clone == null )) )) 
			{
				//line 258 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				int i = ((int) (haxe.lang.Runtime.getField_f(this.clone, "index", true)) );
				//line 259 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if (( ( i >= 0 ) && ( i < a.length ) )) 
				{
					//line 259 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					return a.__get(i);
				}
				else
				{
					//line 259 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					return null;
				}
				
			}
			else
			{
				//line 261 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				int count = ((int) (java.lang.Math.max(((double) (( a.length - 1 )) ), ((double) (0) ))) );
				//line 262 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				if (( this.clones == null )) 
				{
					//line 262 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					this.clones = new haxe.root.Array<ub1.core.Element>(new ub1.core.Element[]{});
				}
				
				//line 264 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				{
					//line 264 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					int _g = 0;
					//line 264 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					int _g1 = count;
					//line 264 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					while (( _g < _g1 ))
					{
						//line 264 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						int i1 = _g++;
						//line 265 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (( i1 >= this.clones.length )) 
						{
							//line 266 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							ub1.core.Element c = this.cloneSelf(i1);
							//line 267 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.clones.push(c);
							//line 268 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							c.context.refresh(c, null);
						}
						
					}
					
				}
				
				//line 272 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				while (( this.clones.length > count ))
				{
					//line 273 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					ub1.core.Element c1 = ((ub1.core.Element) (this.clones.pop()) );
					//line 274 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					ub1.lib.DomTools.domRemove(c1.dom);
					//line 275 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
					if (( c1.baseParent != null )) 
					{
						//line 275 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						c1.baseParent.removeChild(c1);
					}
					
				}
				
				//line 277 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				java.lang.Object ret = ( (( a.length > 0 )) ? (a.__get(( a.length - 1 ))) : (null) );
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				return ret;
			}
			
		}
		else
		{
			//line 281 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			return v;
		}
		
	}
	
	
	public ub1.core.Element cloneSelf(int cloneIndex)
	{
		//line 286 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		java.lang.String html = ub1.lib.DomTools.domOuterHTML(this.dom);
		//line 287 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.server.dom.HtmlElement wrapper = ub1.lib.DomTools.domCreateElement(((ub1.core.Page) (this.baseRoot) ).doc, "div");
		//line 288 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.DomTools.domSetHtml(wrapper, html);
		//line 289 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.server.dom.HtmlElement e = ub1.lib.DomTools.domFirstElementChild(wrapper);
		//line 290 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.DomTools.domSet(e, "data-clone", ( "" + cloneIndex ));
		//line 291 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.lib.DomTools.domAddChild(ub1.lib.DomTools.domParent(this.dom), e, this.dom);
		//line 292 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		ub1.core.Element ret = ((ub1.core.Page) (this.baseRoot) ).load(((ub1.core.Element) (this.baseParent) ), e, cloneIndex);
		//line 293 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return ret;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			boolean __temp_executeDef1 = true;
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( field != null )) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				switch (field.hashCode())
				{
					case 94756189:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("clone")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.clone = ((java.lang.Object) (value) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 3355:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("id")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.id = ((int) (value) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (__temp_executeDef1) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			boolean __temp_executeDef1 = true;
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( field != null )) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				switch (field.hashCode())
				{
					case -1357525322:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("clones")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.clones = ((haxe.root.Array<ub1.core.Element>) (value) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 3506402:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("root")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.root = ((ub1.core.Page) (value) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 94756189:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("clone")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.clone = ((java.lang.Object) (value) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -995424086:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("parent")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.parent = ((ub1.core.Element) (value) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 99650:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("dom")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.dom = ((ub1.server.dom.HtmlElement) (value) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 3355:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("id")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.id = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return value;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (__temp_executeDef1) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			boolean __temp_executeDef1 = true;
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( field != null )) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				switch (field.hashCode())
				{
					case -625661367:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("cloneSelf")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "cloneSelf")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 3506402:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("root")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ( (handleProperties) ? (this.get_root()) : (this.root) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 1155017231:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("dataCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "dataCallback")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 1976619051:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("get_root")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_root")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 267960538:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("initData")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "initData")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -995424086:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("parent")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ( (handleProperties) ? (this.get_parent()) : (this.parent) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 123872696:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("setClones")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "setClones")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 1085254067:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("get_parent")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_parent")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -1357525322:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("clones")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.clones;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 3355:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("id")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.id;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -1996136170:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("styleCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "styleCallback")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 99650:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("dom")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.dom;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 932656605:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("classCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "classCallback")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 94756189:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("clone")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.clone;
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -440447854:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("textCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "textCallback")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -617734511:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("addEventHandler")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "addEventHandler")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 323476822:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("attrCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "attrCallback")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -857280550:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("addValueHandler")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "addValueHandler")) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (__temp_executeDef1) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			boolean __temp_executeDef1 = true;
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( field != null )) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				switch (field.hashCode())
				{
					case 94756189:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("clone")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((double) (haxe.lang.Runtime.toDouble(this.clone)) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 3355:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("id")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return ((double) (this.id) );
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (__temp_executeDef1) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		{
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			boolean __temp_executeDef1 = true;
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (( field != null )) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				switch (field.hashCode())
				{
					case -625661367:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("cloneSelf")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.cloneSelf(((int) (haxe.lang.Runtime.toInt(dynargs[0])) ));
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 1976619051:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("get_root")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.get_root();
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 1155017231:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("dataCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.dataCallback(dynargs[0], haxe.lang.Runtime.toString(dynargs[1]), dynargs[2]);
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 1085254067:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("get_parent")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.get_parent();
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 267960538:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("initData")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.initData();
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -617734511:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("addEventHandler")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.addEventHandler(haxe.lang.Runtime.toString(dynargs[0]), dynargs[1]);
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 123872696:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("setClones")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.setClones(((haxe.root.Array<ub1.core.Element>) (dynargs[0]) ));
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -857280550:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("addValueHandler")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							this.addValueHandler(haxe.lang.Runtime.toString(dynargs[0]), dynargs[1]);
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -1996136170:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("styleCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.styleCallback(dynargs[0], haxe.lang.Runtime.toString(dynargs[1]), haxe.lang.Runtime.toString(dynargs[2]));
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 323476822:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("attrCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.attrCallback(dynargs[0], haxe.lang.Runtime.toString(dynargs[1]), haxe.lang.Runtime.toString(dynargs[2]));
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case 932656605:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("classCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.classCallback(dynargs[0], haxe.lang.Runtime.toString(dynargs[1]), haxe.lang.Runtime.toString(dynargs[2]));
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
					case -440447854:
					{
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						if (field.equals("textCallback")) 
						{
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							__temp_executeDef1 = false;
							//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
							return this.textCallback(dynargs[0], haxe.lang.Runtime.toString(dynargs[1]), ((ub1.server.dom.HtmlText) (dynargs[2]) ));
						}
						
						//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
			if (__temp_executeDef1) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		baseArr.push("clones");
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		baseArr.push("clone");
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		baseArr.push("dom");
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		baseArr.push("id");
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		baseArr.push("parent");
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		baseArr.push("root");
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Element.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


