// Generated by Haxe 4.1.5
package ub1.core;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Head___hx_ctor_ub1_core_Head_13__Fun extends haxe.lang.Function
{
	public Head___hx_ctor_ub1_core_Head_13__Fun()
	{
		//line 14 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		super(1, 0);
	}
	
	
	public static ub1.core.Head___hx_ctor_ub1_core_Head_13__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		java.lang.String s = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (haxe.lang.Runtime.toString(__fn_float1)) : (haxe.lang.Runtime.toString(__fn_dyn1)) );
		//line 14 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		return ( ( ( ( ( ( ( "-moz-" + s ) + ";-webkit-" ) + s ) + ";-ms-" ) + s ) + ";" ) + s );
	}
	
	
}


