// Generated by Haxe 4.1.5
package ub1.core;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Head extends ub1.core.Element
{
	public Head(haxe.lang.EmptyObject empty)
	{
		//line 6 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public Head(ub1.core.Element parent, java.lang.Object props)
	{
		//line 11 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 11 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		ub1.core.Head.__hx_ctor_ub1_core_Head(this, parent, props);
	}
	
	
	protected static void __hx_ctor_ub1_core_Head(ub1.core.Head __hx_this, ub1.core.Element parent, java.lang.Object props)
	{
		//line 9 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		if (( props == null )) 
		{
			//line 9 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
			props = new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{});
		}
		
		//line 10 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		if (( haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(props, "name", true)) == null )) 
		{
			//line 10 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
			java.lang.String __temp_expr1 = haxe.lang.Runtime.toString(haxe.lang.Runtime.setField(props, "name", "head"));
		}
		
		//line 11 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		ub1.core.Element.__hx_ctor_ub1_core_Element(__hx_this, parent, props);
		//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		new ub1.reactivity.ReConst(__hx_this, "cssVendorize", ( (( ub1.core.Head___hx_ctor_ub1_core_Head_13__Fun.__hx_current != null )) ? (ub1.core.Head___hx_ctor_ub1_core_Head_13__Fun.__hx_current) : (ub1.core.Head___hx_ctor_ub1_core_Head_13__Fun.__hx_current = ((ub1.core.Head___hx_ctor_ub1_core_Head_13__Fun) (new ub1.core.Head___hx_ctor_ub1_core_Head_13__Fun()) )) ), null, null, null, null);
		//line 16 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Head.hx"
		new ub1.reactivity.ReConst(__hx_this, "cssVendorize2", ( (( ub1.core.Head___hx_ctor_ub1_core_Head_16__Fun.__hx_current != null )) ? (ub1.core.Head___hx_ctor_ub1_core_Head_16__Fun.__hx_current) : (ub1.core.Head___hx_ctor_ub1_core_Head_16__Fun.__hx_current = ((ub1.core.Head___hx_ctor_ub1_core_Head_16__Fun) (new ub1.core.Head___hx_ctor_ub1_core_Head_16__Fun()) )) ), null, null, null, null);
	}
	
	
}


