// Generated by Haxe 4.1.5
package ub1.core;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Page_load_61__Fun extends haxe.lang.Function
{
	public Page_load_61__Fun(ub1.core.Element ret, ub1.core.Page _gthis)
	{
		//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
		super(1, 0);
		//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
		this.ret = ret;
		//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
		this._gthis = _gthis;
	}
	
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
		ub1.server.dom.HtmlElement dom = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((ub1.server.dom.HtmlElement) (((java.lang.Object) (__fn_float1) )) )) : (((ub1.server.dom.HtmlElement) (__fn_dyn1) )) );
		//line 62 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
		ub1.server.dom.HtmlElement e = ub1.lib.DomTools.domFirstElementChild(dom);
		//line 63 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
		while (( e != null ))
		{
			//line 64 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
			if (( ub1.lib.DomTools.domGet(e, "data-id") != null )) 
			{
				//line 65 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
				this._gthis.load(this.ret, e, null);
			}
			
			//line 67 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
			e = ub1.lib.DomTools.domNextElementSibling(e);
		}
		
		//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/core/Page.hx"
		return null;
	}
	
	
	public ub1.core.Element ret;
	
	public ub1.core.Page _gthis;
	
}


