// Generated by Haxe 4.1.5
package ub1;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Ub1Common extends haxe.lang.HxObject
{
	static
	{
		//line 4 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Common.hx"
		ub1.Ub1Common.PAGE_PROPS_VAR = "ub1Props";
	}
	
	public Ub1Common(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Ub1Common()
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Common.hx"
		ub1.Ub1Common.__hx_ctor_ub1_Ub1Common(this);
	}
	
	
	protected static void __hx_ctor_ub1_Ub1Common(ub1.Ub1Common __hx_this)
	{
	}
	
	
	public static java.lang.String PAGE_PROPS_VAR;
	
}


