// Generated by Haxe 4.1.5
package ub1;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Ub1Server extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		haxe.java.Init.init();
		ub1.Ub1Server.main();
	}
	
	public Ub1Server(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Ub1Server()
	{
		//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.Ub1Server.__hx_ctor_ub1_Ub1Server(this);
	}
	
	
	protected static void __hx_ctor_ub1_Ub1Server(ub1.Ub1Server __hx_this)
	{
	}
	
	
	public static void main()
	{
	}
	
	
	public static ub1.core.Page load(java.lang.String root, java.lang.String uri, java.lang.String domain, java.lang.Object addClient)
	{
		//line 17 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		boolean addClient1 = ( (haxe.lang.Runtime.eq(addClient, null)) ? (true) : (haxe.lang.Runtime.toBool(((java.lang.Boolean) (addClient) ))) );
		//line 17 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		if (( domain == null )) 
		{
			//line 17 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
			domain = "localhost";
		}
		
		//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.lib.Url url = new ub1.lib.Url(uri, null);
		//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.server.dom.HtmlDocument doc = new ub1.server.Preprocessor(haxe.lang.Runtime.toString(root)).read(url.path);
		//line 20 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.core.Page page = ub1.server.ServerLoader.loadRoot(doc);
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		page.context.refresh(null, null);
		//line 22 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		if (addClient1) 
		{
			//line 23 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
			ub1.Ub1Server.addClient(page);
		}
		
		//line 25 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		return page;
	}
	
	
	public static void addClient(ub1.core.Page p)
	{
		//line 31 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.server.dom.HtmlElement e = new ub1.server.dom.HtmlElement(ub1.lib.DomTools.domGetBody(p.doc), "script", 0, 0, 0);
		//line 32 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		haxe.lang.Function replacer = null;
		//line 32 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		java.lang.String space = null;
		//line 32 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		java.lang.String s = ( ( ( "ub1Props" + " = " ) + haxe.format.JsonPrinter.print(((java.lang.Object) (p.getProps()) ), replacer, space) ) + ";" );
		//line 33 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		new ub1.server.dom.HtmlText(e, s, 0, 0, 0, false);
		//line 35 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.server.dom.HtmlElement e1 = ub1.lib.DomTools.domCreateElement(p.doc, "script");
		//line 36 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.lib.DomTools.domSet(e1, "src", "/.ub1/client/ub1.js");
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/Ub1Server.hx"
		ub1.lib.DomTools.domAddChild(ub1.lib.DomTools.domGetBody(p.doc), e1, null);
	}
	
	
}


