// Generated by Haxe 4.1.5
package haxe;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public interface IMap<K, V> extends haxe.lang.IHxObject
{
	java.lang.Object get(K k);
	
	void set(K k, V v);
	
	boolean exists(K k);
	
	boolean remove(K k);
	
	java.lang.Object keys();
	
	java.lang.String toString();
	
}


