// Generated by Haxe 4.1.5
package ub1.reactivity;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Applier extends ub1.lib.DoubleLinkedItem
{
	public Applier(haxe.lang.EmptyObject empty)
	{
		//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		super(((haxe.lang.EmptyObject) (haxe.lang.EmptyObject.EMPTY) ));
	}
	
	
	public Applier(haxe.lang.Function cb)
	{
		//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		super(haxe.lang.EmptyObject.EMPTY);
		//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		ub1.reactivity.Applier.__hx_ctor_ub1_reactivity_Applier(this, cb);
	}
	
	
	protected static void __hx_ctor_ub1_reactivity_Applier(ub1.reactivity.Applier __hx_this, haxe.lang.Function cb)
	{
		//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		ub1.lib.DoubleLinkedItem.__hx_ctor_ub1_lib_DoubleLinkedItem(__hx_this);
		//line 184 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		__hx_this.cb = cb;
	}
	
	
	public haxe.lang.Function cb;
	
	public final void apply()
	{
		//line 188 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		this.cb.__hx_invoke0_o();
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		{
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			boolean __temp_executeDef1 = true;
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			if (( field != null )) 
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				switch (field.hashCode())
				{
					case 3167:
					{
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						if (field.equals("cb")) 
						{
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							__temp_executeDef1 = false;
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							this.cb = ((haxe.lang.Function) (value) );
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							return value;
						}
						
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			if (__temp_executeDef1) 
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		{
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			boolean __temp_executeDef1 = true;
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			if (( field != null )) 
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				switch (field.hashCode())
				{
					case 93029230:
					{
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						if (field.equals("apply")) 
						{
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							__temp_executeDef1 = false;
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "apply")) );
						}
						
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						break;
					}
					
					
					case 3167:
					{
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						if (field.equals("cb")) 
						{
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							__temp_executeDef1 = false;
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							return this.cb;
						}
						
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			if (__temp_executeDef1) 
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		{
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			boolean __temp_executeDef1 = true;
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			if (( field != null )) 
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				switch (field.hashCode())
				{
					case 93029230:
					{
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						if (field.equals("apply")) 
						{
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							__temp_executeDef1 = false;
							//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
							this.apply();
						}
						
						//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
			if (__temp_executeDef1) 
			{
				//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		baseArr.push("cb");
		//line 179 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReContext.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


