// Generated by Haxe 4.1.5
package ub1.reactivity;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ReScope_countScopes_150__Fun extends haxe.lang.Function
{
	public ReScope_countScopes_150__Fun()
	{
		//line 150 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		super(1, 1);
	}
	
	
	public static ub1.reactivity.ReScope_countScopes_150__Fun __hx_current;
	
	@Override public double __hx_invoke1_f(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 150 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		ub1.reactivity.ReScope scope = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((ub1.reactivity.ReScope) (((java.lang.Object) (__fn_float1) )) )) : (((ub1.reactivity.ReScope) (__fn_dyn1) )) );
		//line 151 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		int ret = 1;
		//line 152 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		{
			//line 152 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
			int _g = 0;
			//line 152 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
			haxe.root.Array<ub1.reactivity.ReScope> _g1 = ((haxe.root.Array<ub1.reactivity.ReScope>) (((haxe.root.Array) (scope.get_baseChildren()) )) );
			//line 152 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
			while (( _g < _g1.length ))
			{
				//line 152 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
				ub1.reactivity.ReScope child = _g1.__get(_g);
				//line 152 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
				 ++ _g;
				//line 153 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
				ret += child.countScopes();
			}
			
		}
		
		//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		return ((double) (ret) );
	}
	
	
}


