// Generated by Haxe 4.1.5
package ub1.reactivity;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ReScope___hx_ctor_ub1_reactivity_ReScope_46__Fun extends haxe.lang.Function
{
	public ReScope___hx_ctor_ub1_reactivity_ReScope_46__Fun()
	{
		//line 46 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		super(1, 0);
	}
	
	
	public static ub1.reactivity.ReScope___hx_ctor_ub1_reactivity_ReScope_46__Fun __hx_current;
	
	@Override public java.lang.Object __hx_invoke1_o(double __fn_float1, java.lang.Object __fn_dyn1)
	{
		//line 46 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		haxe.root.Array el = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (((haxe.root.Array) (((java.lang.Object) (__fn_float1) )) )) : (((haxe.root.Array) (__fn_dyn1) )) );
		//line 46 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/reactivity/ReScope.hx"
		return null;
	}
	
	
}


