// Generated by Haxe 4.1.5
package ub1.server;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class HtmlParser extends haxe.lang.HxObject
{
	static
	{
		//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		ub1.server.HtmlParser.SKIP_CONTENT_TAGS = new haxe.lang.DynamicObject(new java.lang.String[]{"SCRIPT", "STYLE"}, new java.lang.Object[]{true, true}, new java.lang.String[]{}, new double[]{});
	}
	
	public HtmlParser(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public HtmlParser()
	{
		//line 20 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		ub1.server.HtmlParser.__hx_ctor_ub1_server_HtmlParser(this);
	}
	
	
	protected static void __hx_ctor_ub1_server_HtmlParser(ub1.server.HtmlParser __hx_this)
	{
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		__hx_this.origins = new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
	}
	
	
	public static java.lang.Object SKIP_CONTENT_TAGS;
	
	public static ub1.server.dom.HtmlDocument parse(java.lang.String s)
	{
		//line 17 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return new ub1.server.HtmlParser().parseDoc(s, null);
	}
	
	
	public haxe.root.Array<java.lang.String> origins;
	
	public ub1.server.dom.HtmlDocument parseDoc(java.lang.String s, java.lang.String fname)
	{
		//line 25 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if (( fname == null )) 
		{
			//line 25 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			fname = "literal";
		}
		
		//line 26 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int origin = this.origins.length;
		//line 27 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		this.origins.push(fname);
		//line 28 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		ub1.server.dom.HtmlDocument ret = new ub1.server.dom.HtmlDocument(((int) (origin) ));
		//line 29 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int i = this.parseNodes(ret, s, 0, origin);
		//line 30 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if (( i < s.length() )) 
		{
			//line 31 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			new ub1.server.dom.HtmlText(ret, haxe.lang.StringExt.substr(s, i, null), i, s.length(), origin, null);
		}
		
		//line 33 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return ret;
	}
	
	
	public int parseNodes(ub1.server.dom.HtmlElement p, java.lang.String s, int i1, int origin)
	{
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int i2 = 0;
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		boolean closure = false;
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int i3 = i1;
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int i4 = 0;
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		java.lang.String closetag = null;
		//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		while (true)
		{
			//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i2 = haxe.lang.StringExt.indexOf(s, "<", i1);
			//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if ( ! ((( i2 >= 0 ))) ) 
			{
				//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				break;
			}
			
			//line 39 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i4 = i2;
			//line 40 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 = ( i2 + 1 );
			//line 41 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			closure = haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i1), 47);
			//line 41 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (closure) 
			{
				//line 41 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				 ++ i1;
			}
			
			//line 42 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i2 = this.skipName(s, i1);
			//line 42 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( i2 > i1 )) 
			{
				//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				if (( i4 > i3 )) 
				{
					//line 44 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					new ub1.server.dom.HtmlText(p, haxe.lang.StringExt.substring(s, i3, i4), i3, i4, origin, false);
				}
				
				//line 46 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				if (closure) 
				{
					//line 47 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					java.lang.String name = haxe.lang.StringExt.substring(s, i1, i2).toUpperCase();
					//line 48 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					if (haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i2), 62)) 
					{
						//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (haxe.lang.Runtime.valEq(name, p.name)) 
						{
							//line 50 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							i1 = ( i2 + 1 );
							//line 51 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							closetag = name;
							//line 52 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							break;
						}
						else
						{
							//line 54 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							throw new ub1.server.HtmlException(( ( ( ( "Found </" + name ) + "> instead of </" ) + p.name ) + ">" ), this.origins.__get(origin), i1, s);
						}
						
					}
					else
					{
						//line 60 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						throw new ub1.server.HtmlException(( "Unterminated close tag " + name ), this.origins.__get(origin), i1, s);
					}
					
				}
				else
				{
					//line 67 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					i1 = this.parseElement(p, s, i1, i2, origin);
				}
				
				//line 69 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				i3 = i1;
			}
			else
			{
				//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				boolean tmp = false;
				//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				if ( ! (closure) ) 
				{
					//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					i2 = this.skipComment(s, i1, origin);
					//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					tmp = ( i2 > i1 );
				}
				else
				{
					//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					tmp = false;
				}
				
				//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				if (tmp) 
				{
					//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					if (( i4 > i3 )) 
					{
						//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						new ub1.server.dom.HtmlText(p, haxe.lang.StringExt.substring(s, i3, i4), i3, i4, origin, false);
					}
					
					//line 74 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					if (( ! (haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, ( i1 + 3 )), 45)) )) 
					{
						//line 76 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						new ub1.server.dom.HtmlComment(p, haxe.lang.StringExt.substring(s, ( i1 - 1 ), i2), ( i1 - 1 ), i2, origin);
					}
					
					//line 78 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					i1 = i2;
					//line 78 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					i3 = i1;
				}
				
			}
			
		}
		
		//line 81 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if ( ! (haxe.lang.Runtime.valEq(closetag, p.name)) ) 
		{
			//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			throw new ub1.server.HtmlException(( ( "expected </" + p.name ) + ">" ), this.origins.__get(origin), i1, s);
		}
		
		//line 84 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return i1;
	}
	
	
	public int parseElement(ub1.server.dom.HtmlElement p, java.lang.String s, int i1, int i2, int origin)
	{
		//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		ub1.server.dom.HtmlElement e = new ub1.server.dom.HtmlElement(p, haxe.lang.StringExt.substring(s, i1, i2), i1, i2, origin);
		//line 89 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		i1 = this.parseAttributes(e, s, i2, origin);
		//line 90 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		i1 = this.skipBlanks(s, i1);
		//line 91 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		boolean selfclose = false;
		//line 92 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		selfclose = haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i1), 47);
		//line 92 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if (selfclose) 
		{
			//line 93 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			 ++ i1;
		}
		
		//line 95 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if (( ! (haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i1), 62)) )) 
		{
			//line 96 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			throw new ub1.server.HtmlException(( "Unterminated tag " + e.name ), this.origins.__get(origin), i1, s);
		}
		
		//line 101 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		 ++ i1;
		//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if ((  ! (selfclose)  &&  ! (ub1.lib.PropertyTools.exists(ub1.server.dom.HtmlElement.VOID_ELEMENTS, e.name))  )) 
		{
			//line 103 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (ub1.lib.PropertyTools.exists(ub1.server.HtmlParser.SKIP_CONTENT_TAGS, e.name)) 
			{
				//line 104 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				java.lang.Object res = this.skipContent(e.name, s, i1, origin);
				//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				if (( res == null )) 
				{
					//line 106 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					throw new ub1.server.HtmlException(( "Unterminated tag " + e.name ), this.origins.__get(origin), i1, s);
				}
				
				//line 111 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				new ub1.server.dom.HtmlText(e, haxe.lang.StringExt.substring(s, i1, ((int) (haxe.lang.Runtime.getField_f(res, "i0", true)) )), i1, ((int) (haxe.lang.Runtime.getField_f(res, "i0", true)) ), origin, false);
				//line 112 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				i1 = ((int) (haxe.lang.Runtime.getField_f(res, "i2", true)) );
			}
			else
			{
				//line 114 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				i1 = this.parseNodes(e, s, i1, origin);
			}
			
		}
		
		//line 117 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return i1;
	}
	
	
	public int parseAttributes(ub1.server.dom.HtmlElement e, java.lang.String s, int i2, int origin)
	{
		//line 121 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int i1 = this.skipBlanks(s, i2);
		//line 122 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		while (true)
		{
			//line 122 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i2 = this.skipName(s, i1);
			//line 122 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if ( ! ((( i2 > i1 ))) ) 
			{
				//line 122 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				break;
			}
			
			//line 123 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			java.lang.String name = haxe.lang.StringExt.substring(s, i1, i2);
			//line 124 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			ub1.server.dom.HtmlAttribute a = e.setAttribute(name, "", null, i1, i2, origin);
			//line 125 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 = this.skipBlanks(s, i2);
			//line 126 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i1), 61)) 
			{
				//line 127 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				i1 = this.skipBlanks(s, ( i1 + 1 ));
				//line 128 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				java.lang.Object quote = haxe.lang.StringExt.charCodeAt(s, i1);
				//line 129 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				if (( haxe.lang.Runtime.eq(quote, 34) || haxe.lang.Runtime.eq(quote, 39) )) 
				{
					//line 130 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					i1 = this.parseValue(a, s, ( i1 + 1 ), ((int) (haxe.lang.Runtime.toInt(quote)) ), new java.lang.String( java.lang.Character.toChars((int) ((int) (haxe.lang.Runtime.toInt(quote)) )) ), origin);
				}
				else
				{
					//line 132 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					if (( haxe.lang.Runtime.eq(quote, 91) && haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, ( i1 + 1 )), 91) )) 
					{
						//line 133 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						i1 = this.parseValue(a, s, ( i1 + 2 ), ((int) (haxe.lang.Runtime.toInt(quote)) ), "]]", origin);
					}
					else
					{
						//line 136 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						throw new ub1.server.HtmlException("Missing attribute value", this.origins.__get(origin), i1, s);
					}
					
				}
				
			}
			
			//line 141 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 = this.skipBlanks(s, i1);
		}
		
		//line 143 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return i1;
	}
	
	
	public int parseValue(ub1.server.dom.HtmlAttribute a, java.lang.String s, int i1, int quote, java.lang.String term, int origin)
	{
		//line 148 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int i2 = haxe.lang.StringExt.indexOf(s, term, i1);
		//line 149 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if (( i2 < 0 )) 
		{
			//line 150 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			throw new ub1.server.HtmlException("Unterminated attribute value", this.origins.__get(origin), i1, s);
		}
		else
		{
			//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			a.quote = new java.lang.String( java.lang.Character.toChars((int) quote) );
			//line 156 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			int i = ( i2 + term.length() );
			//line 157 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			while (( ( i < s.length() ) && haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i), haxe.lang.StringExt.charCodeAt(term, 0)) ))
			{
				//line 158 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				 ++ i2;
				//line 158 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				 ++ i;
			}
			
			//line 160 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			a.value = haxe.lang.StringExt.substring(s, i1, i2);
			//line 161 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 = ( i2 + term.length() );
		}
		
		//line 163 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return i1;
	}
	
	
	public int skipComment(java.lang.String s, int i1, int origin)
	{
		//line 167 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		if (( ( haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i1), 33) && haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, ( i1 + 1 )), 45) ) && haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, ( i1 + 2 )), 45) )) 
		{
			//line 170 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 = haxe.lang.StringExt.indexOf(s, "-->", ( i1 + 3 ));
			//line 170 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( i1 < 0 )) 
			{
				//line 171 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				throw new ub1.server.HtmlException("Unterminated comment", this.origins.__get(origin), i1, s);
			}
			
			//line 176 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 += 3;
		}
		
		//line 178 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return i1;
	}
	
	
	public java.lang.Object skipContent(java.lang.String tag, java.lang.String s, int i1, int origin)
	{
		//line 182 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		int i2 = 0;
		//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		while (true)
		{
			//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i2 = haxe.lang.StringExt.indexOf(s, "</", i1);
			//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if ( ! ((( i2 >= 0 ))) ) 
			{
				//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				break;
			}
			
			//line 184 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			int i0 = i2;
			//line 185 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 = ( i2 + 2 );
			//line 186 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i2 = this.skipName(s, i1);
			//line 187 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( i2 > i1 )) 
			{
				//line 188 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				if (haxe.lang.Runtime.valEq(haxe.lang.StringExt.substring(s, i1, i2).toUpperCase(), tag)) 
				{
					//line 189 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					i2 = this.skipBlanks(s, i2);
					//line 190 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					if (( ! (haxe.lang.Runtime.eq(haxe.lang.StringExt.charCodeAt(s, i2), 62)) )) 
					{
						//line 191 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						throw new ub1.server.HtmlException("Unterminated close tag", this.origins.__get(origin), i1, s);
					}
					
					//line 196 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					 ++ i2;
					//line 198 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
					return new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{"i0", "i2"}, new double[]{((double) (((double) (i0) )) ), ((double) (((double) (i2) )) )});
				}
				
			}
			
			//line 201 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			i1 = i2;
		}
		
		//line 203 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return null;
	}
	
	
	public int skipBlanks(java.lang.String s, int i)
	{
		//line 207 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		while (( i < s.length() ))
		{
			//line 208 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( ((int) (haxe.lang.Runtime.toInt(haxe.lang.StringExt.charCodeAt(s, i))) ) > 32 )) 
			{
				//line 209 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				break;
			}
			
			//line 211 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			 ++ i;
		}
		
		//line 213 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return i;
	}
	
	
	public int skipName(java.lang.String s, int i)
	{
		//line 217 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		while (( i < s.length() ))
		{
			//line 218 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			java.lang.Object code = haxe.lang.StringExt.charCodeAt(s, i);
			//line 219 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( ( ( ( ( (( ( ((int) (haxe.lang.Runtime.toInt(code)) ) < 97 ) || ( ((int) (haxe.lang.Runtime.toInt(code)) ) > 122 ) )) && (( ( ((int) (haxe.lang.Runtime.toInt(code)) ) < 65 ) || ( ((int) (haxe.lang.Runtime.toInt(code)) ) > 90 ) )) ) && (( ( ((int) (haxe.lang.Runtime.toInt(code)) ) < 48 ) || ( ((int) (haxe.lang.Runtime.toInt(code)) ) > 57 ) )) ) && ( ! (haxe.lang.Runtime.eq(code, 45)) ) ) && ( ! (haxe.lang.Runtime.eq(code, 95)) ) ) && ( ! (haxe.lang.Runtime.eq(code, 58)) ) )) 
			{
				//line 223 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				break;
			}
			
			//line 225 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			 ++ i;
		}
		
		//line 227 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		return i;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		{
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			boolean __temp_executeDef1 = true;
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( field != null )) 
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				switch (field.hashCode())
				{
					case -1202440691:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("origins")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							this.origins = ((haxe.root.Array<java.lang.String>) (value) );
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return value;
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (__temp_executeDef1) 
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		{
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			boolean __temp_executeDef1 = true;
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( field != null )) 
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				switch (field.hashCode())
				{
					case 2145254570:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipName")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "skipName")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -1202440691:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("origins")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.origins;
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -328396802:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipBlanks")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "skipBlanks")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case 1187778949:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseDoc")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "parseDoc")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -604796422:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipContent")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "skipContent")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -996491330:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseNodes")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "parseNodes")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -605928480:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipComment")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "skipComment")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case 667204809:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseElement")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "parseElement")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -989512066:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseValue")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "parseValue")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -580379542:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseAttributes")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "parseAttributes")) );
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (__temp_executeDef1) 
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		{
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			boolean __temp_executeDef1 = true;
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (( field != null )) 
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				switch (field.hashCode())
				{
					case 2145254570:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipName")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.skipName(haxe.lang.Runtime.toString(dynargs[0]), ((int) (haxe.lang.Runtime.toInt(dynargs[1])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case 1187778949:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseDoc")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.parseDoc(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(( (( dynargs.length > 1 )) ? (dynargs[1]) : (null) )));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -328396802:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipBlanks")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.skipBlanks(haxe.lang.Runtime.toString(dynargs[0]), ((int) (haxe.lang.Runtime.toInt(dynargs[1])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -996491330:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseNodes")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.parseNodes(((ub1.server.dom.HtmlElement) (dynargs[0]) ), haxe.lang.Runtime.toString(dynargs[1]), ((int) (haxe.lang.Runtime.toInt(dynargs[2])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -604796422:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipContent")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.skipContent(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(dynargs[1]), ((int) (haxe.lang.Runtime.toInt(dynargs[2])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case 667204809:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseElement")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.parseElement(((ub1.server.dom.HtmlElement) (dynargs[0]) ), haxe.lang.Runtime.toString(dynargs[1]), ((int) (haxe.lang.Runtime.toInt(dynargs[2])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[4])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -605928480:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("skipComment")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.skipComment(haxe.lang.Runtime.toString(dynargs[0]), ((int) (haxe.lang.Runtime.toInt(dynargs[1])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[2])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -580379542:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseAttributes")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.parseAttributes(((ub1.server.dom.HtmlElement) (dynargs[0]) ), haxe.lang.Runtime.toString(dynargs[1]), ((int) (haxe.lang.Runtime.toInt(dynargs[2])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
					case -989512066:
					{
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						if (field.equals("parseValue")) 
						{
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							__temp_executeDef1 = false;
							//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
							return this.parseValue(((ub1.server.dom.HtmlAttribute) (dynargs[0]) ), haxe.lang.Runtime.toString(dynargs[1]), ((int) (haxe.lang.Runtime.toInt(dynargs[2])) ), ((int) (haxe.lang.Runtime.toInt(dynargs[3])) ), haxe.lang.Runtime.toString(dynargs[4]), ((int) (haxe.lang.Runtime.toInt(dynargs[5])) ));
						}
						
						//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
			if (__temp_executeDef1) 
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		baseArr.push("origins");
		//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/HtmlParser.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


