// Generated by Haxe 4.1.5
package ub1.server;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Preprocessor extends haxe.lang.HxObject
{
	static
	{
		//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.INCLUDE_TAG = ":INCLUDE";
		//line 44 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.IMPORT_TAG = ":IMPORT";
		//line 45 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.INCLUDE_ARG = "src";
		//line 109 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.DEFINE_TAG = ":DEFINE";
		//line 110 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.DEFINE_ARG = "tag";
		//line 111 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.SLOT_TAG = ":SLOT";
		//line 112 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.SLOT_ARG = "name";
		//line 113 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.SLOT_ATTR = ":slot";
	}
	
	public Preprocessor(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Preprocessor(java.lang.String rootPath)
	{
		//line 27 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor.__hx_ctor_ub1_server_Preprocessor(this, rootPath);
	}
	
	
	protected static void __hx_ctor_ub1_server_Preprocessor(ub1.server.Preprocessor __hx_this, java.lang.String rootPath)
	{
		//line 28 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.rootPath = haxe.io.Path.addTrailingSlash(haxe.io.Path.normalize(rootPath));
		//line 29 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.parser = new ub1.server.HtmlParser();
		//line 30 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.sources = new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
		//line 31 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.macros = new haxe.ds.StringMap<java.lang.Object>();
	}
	
	
	public static java.lang.String INCLUDE_TAG;
	
	public static java.lang.String IMPORT_TAG;
	
	public static java.lang.String INCLUDE_ARG;
	
	public static java.lang.String DEFINE_TAG;
	
	public static java.lang.String DEFINE_ARG;
	
	public static java.lang.String SLOT_TAG;
	
	public static java.lang.String SLOT_ARG;
	
	public static java.lang.String SLOT_ATTR;
	
	public java.lang.String rootPath;
	
	public ub1.server.HtmlParser parser;
	
	public haxe.root.Array<java.lang.String> sources;
	
	public haxe.ds.StringMap<java.lang.Object> macros;
	
	public ub1.server.dom.HtmlDocument read(java.lang.String fname)
	{
		//line 35 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.dom.HtmlDocument ret = this.readFile(fname, null, null);
		//line 36 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		this.processMacros(ret);
		//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		return ret;
	}
	
	
	public ub1.server.dom.HtmlDocument readFile(java.lang.String fname, java.lang.String currPath, java.lang.Object once)
	{
		//line 47 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		boolean once1 = ( (haxe.lang.Runtime.eq(once, null)) ? (false) : (haxe.lang.Runtime.toBool(((java.lang.Boolean) (once) ))) );
		//line 48 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.dom.HtmlDocument ret = null;
		//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (((java.lang.String) (((java.lang.Object) (fname) )) ).startsWith(haxe.lang.Runtime.toString("/"))) 
		{
			//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			currPath = null;
		}
		
		//line 50 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( currPath == null )) 
		{
			//line 50 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			currPath = this.rootPath;
		}
		
		//line 51 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		java.lang.String filePath = haxe.io.Path.normalize(haxe.io.Path.join(new haxe.root.Array<java.lang.String>(new java.lang.String[]{currPath, fname})));
		//line 52 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		currPath = haxe.io.Path.directory(filePath);
		//line 53 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if ( ! (((java.lang.String) (((java.lang.Object) (filePath) )) ).startsWith(haxe.lang.Runtime.toString(this.rootPath))) ) 
		{
			//line 54 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new ub1.server.PreprocessorError(( ( "Forbidden file path \"" + fname ) + "\"" ), null, null, null, null))) );
		}
		
		//line 56 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( once1 && ( this.parser.origins.indexOf(filePath, null) >= 0 ) )) 
		{
			//line 57 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			return null;
		}
		
		//line 59 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		java.lang.String html = null;
		//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		try 
		{
			//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			html = sys.io.File.getContent(filePath);
		}
		catch (java.lang.Throwable _g)
		{
			//line 63 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new ub1.server.PreprocessorError(( "Could not read file " + fname ), null, null, null, null))) );
		}
		
		
		//line 65 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		try 
		{
			//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			this.sources.push(html);
			//line 67 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ret = this.parser.parseDoc(html, filePath);
			//line 68 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			this.processIncludes(ret, currPath);
		}
		catch (ub1.server.HtmlException ex)
		{
			//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new ub1.server.PreprocessorError(ex.msg, ex.fname, this.rootPath, ex.row, ex.col))) );
		}
		
		catch (java.lang.Throwable _g1)
		{
			//line 1 "?"
			java.lang.Object ex1 = ((java.lang.Object) (haxe.Exception.caught(_g1).unwrap()) );
			//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new ub1.server.PreprocessorError(( "" + haxe.root.Std.string(ex1) ), null, null, null, null))) );
		}
		
		
		//line 74 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		return ret;
	}
	
	
	public void processIncludes(ub1.server.dom.HtmlDocument doc, java.lang.String currPath)
	{
		//line 78 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.ds.StringMap<java.lang.Object> tags = new haxe.ds.StringMap<java.lang.Object>();
		//line 79 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		tags.set(":INCLUDE", true);
		//line 80 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		tags.set(":IMPORT", true);
		//line 81 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.root.Array<ub1.server.dom.HtmlElement> includes = this.lookupTags(doc, tags);
		//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			int _g = 0;
			//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			while (( _g < includes.length ))
			{
				//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				ub1.server.dom.HtmlElement e = includes.__get(_g);
				//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				 ++ _g;
				//line 83 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				this.processInclude(e, ub1.lib.DomTools.domGet(e, "src"), haxe.lang.Runtime.valEq(e.name, ":IMPORT"), currPath);
			}
			
		}
		
	}
	
	
	public void processInclude(ub1.server.dom.HtmlElement e, java.lang.String src, boolean once, java.lang.String currPath)
	{
		//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		boolean tmp = false;
		//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( src != null )) 
		{
			//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			src = ((java.lang.String) (((java.lang.Object) (src) )) ).trim();
			//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			tmp = ( src.length() == 0 );
		}
		else
		{
			//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			tmp = true;
		}
		
		//line 88 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (tmp) 
		{
			//line 89 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			throw new ub1.server.HtmlException("Missing \"src\" attribute", this.parser.origins.__get(e.origin), e.i1, this.sources.__get(e.origin));
		}
		
		//line 94 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.dom.HtmlElement parent = ub1.lib.DomTools.domParent(e);
		//line 95 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.dom.HtmlNode before = ub1.lib.DomTools.domNextSibling(e);
		//line 96 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		e.remove();
		//line 97 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.dom.HtmlDocument doc = this.readFile(src, currPath, once);
		//line 98 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( doc != null )) 
		{
			//line 99 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ub1.server.dom.HtmlElement root = ub1.lib.DomTools.domGetRootElement(doc);
			//line 100 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			{
				//line 100 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				int _g = 0;
				//line 100 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				haxe.root.Array<ub1.server.dom.HtmlNode> _g1 = root.children.copy();
				//line 100 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				while (( _g < _g1.length ))
				{
					//line 100 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					ub1.server.dom.HtmlNode n = _g1.__get(_g);
					//line 100 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					 ++ _g;
					//line 101 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					ub1.lib.DomTools.domAddChild(parent, n.remove(), before);
				}
				
			}
			
		}
		
	}
	
	
	public void processMacros(ub1.server.dom.HtmlDocument doc)
	{
		//line 116 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		this.collectMacros(doc);
		//line 117 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		this.expandMacros(doc);
	}
	
	
	public void collectMacros(ub1.server.dom.HtmlElement p)
	{
		//line 125 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.ds.StringMap<java.lang.Object> tags = new haxe.ds.StringMap<java.lang.Object>();
		//line 126 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		tags.set(":DEFINE", true);
		//line 127 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.root.Array<ub1.server.dom.HtmlElement> macros = this.lookupTags(p, tags);
		//line 128 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 128 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			int _g = 0;
			//line 128 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			while (( _g < macros.length ))
			{
				//line 128 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				ub1.server.dom.HtmlElement e = macros.__get(_g);
				//line 128 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				 ++ _g;
				//line 129 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				this.collectMacro(e);
			}
			
		}
		
	}
	
	
	public void collectMacro(ub1.server.dom.HtmlElement e)
	{
		//line 134 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		java.lang.String tag = ub1.lib.DomTools.domGet(e, "tag");
		//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		boolean tmp = false;
		//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( tag != null )) 
		{
			//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			tag = ((java.lang.String) (((java.lang.Object) (tag) )) ).trim();
			//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			tmp = ( tag.length() == 0 );
		}
		else
		{
			//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			tmp = true;
		}
		
		//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (tmp) 
		{
			//line 136 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			throw new ub1.server.HtmlException(this.parser.origins.__get(e.origin), "Missing \"tag\" attribute", e.i1, this.sources.__get(e.origin));
		}
		
		//line 141 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.root.Array<java.lang.String> names = haxe.lang.StringExt.split(tag, ":");
		//line 142 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( names.length < 2 )) 
		{
			//line 142 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			names.push("div");
		}
		
		//line 143 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if ((  ! (new haxe.root.EReg("^[_a-zA-Z0-9]+-[-:_a-zA-Z0-9]+$", "").match(names.__get(0)))  ||  ! (new haxe.root.EReg("^[-_a-zA-Z0-9]+$", "").match(names.__get(1)))  )) 
		{
			//line 145 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			throw new ub1.server.HtmlException(this.parser.origins.__get(e.origin), "Bad \"tag\" attribute", e.i1, this.sources.__get(e.origin));
		}
		
		//line 150 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		names.__set(0, names.__get(0).toUpperCase());
		//line 151 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		names.__set(1, names.__get(1).toUpperCase());
		//line 152 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		e.remove();
		//line 153 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.lib.DomTools.domSet(e, "tag", null);
		//line 154 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		this.expandMacros(e);
		//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			haxe.IMap<java.lang.String, java.lang.Object> this1 = this.macros;
			//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			java.lang.Object value = null;
			//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			{
				//line 156 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.String __temp_odecl1 = names.__get(0);
				//line 157 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.String __temp_odecl2 = names.__get(1);
				//line 159 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.Object __temp_odecl3 = ((haxe.ds.StringMap<java.lang.Object>) (((haxe.IMap<java.lang.String, java.lang.Object>) (this.macros) )) ).get(names.__get(1));
				//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				value = new haxe.lang.DynamicObject(new java.lang.String[]{"e", "ext", "name1", "name2"}, new java.lang.Object[]{e, __temp_odecl3, __temp_odecl1, __temp_odecl2}, new java.lang.String[]{}, new double[]{});
			}
			
			//line 155 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			((haxe.ds.StringMap<java.lang.Object>) (this1) ).set(names.__get(0), value);
		}
		
	}
	
	
	public haxe.ds.StringMap<ub1.server.dom.HtmlElement> collectSlots(ub1.server.dom.HtmlElement p)
	{
		//line 164 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.ds.StringMap<ub1.server.dom.HtmlElement> ret = new haxe.ds.StringMap<ub1.server.dom.HtmlElement>();
		//line 165 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.ds.StringMap<java.lang.Object> tags = new haxe.ds.StringMap<java.lang.Object>();
		//line 166 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		tags.set(":SLOT", true);
		//line 167 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.root.Array<ub1.server.dom.HtmlElement> slots = this.lookupTags(p, tags);
		//line 168 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 168 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			int _g = 0;
			//line 168 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			while (( _g < slots.length ))
			{
				//line 168 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				ub1.server.dom.HtmlElement e = slots.__get(_g);
				//line 168 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				 ++ _g;
				//line 169 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.String name = ub1.lib.DomTools.domGet(e, "name");
				//line 170 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				boolean tmp = false;
				//line 170 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				if (( name != null )) 
				{
					//line 171 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					name = ((java.lang.String) (((java.lang.Object) (name) )) ).trim();
					//line 170 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					tmp = ( name.length() < 1 );
				}
				else
				{
					//line 170 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					tmp = true;
				}
				
				//line 170 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				if (( tmp || ret.exists(name) )) 
				{
					//line 173 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					throw new ub1.server.HtmlException(this.parser.origins.__get(e.origin), "Bad \"name\" attribute", e.i1, this.sources.__get(e.origin));
				}
				
				//line 178 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				ret.set(name, e);
			}
			
		}
		
		//line 180 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if ( ! (ret.exists("default")) ) 
		{
			//line 181 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ub1.server.dom.HtmlElement e1 = new ub1.server.dom.HtmlElement(p, ":SLOT", p.i1, p.i2, p.origin);
			//line 182 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ub1.lib.DomTools.domSet(e1, "name", "default");
			//line 183 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ret.set("default", e1);
		}
		
		//line 185 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		return ret;
	}
	
	
	public void expandMacros(ub1.server.dom.HtmlElement p)
	{
		//line 193 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.lang.Function f = null;
		//line 192 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.Preprocessor _gthis = this;
		//line 194 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		f = new ub1.server.Preprocessor_expandMacros_194__Fun(_gthis);
		//line 209 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		f.__hx_invoke1_o(0.0, p);
	}
	
	
	public ub1.server.dom.HtmlElement expandMacro(ub1.server.dom.HtmlElement use, java.lang.Object def)
	{
		//line 213 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.dom.HtmlElement ret = null;
		//line 214 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( ! (( haxe.lang.Runtime.getField(def, "ext", true) == null )) )) 
		{
			//line 215 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ret = this.expandMacro(((ub1.server.dom.HtmlElement) (haxe.lang.Runtime.getField(def, "e", true)) ), haxe.lang.Runtime.getField(def, "ext", true));
		}
		else
		{
			//line 217 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ret = new ub1.server.dom.HtmlElement(null, haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(def, "name2", true)), use.i1, use.i2, use.origin);
			//line 218 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			{
				//line 218 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.Object a = ((java.lang.Object) (new haxe.ds._StringMap.StringMapValueIterator<ub1.server.dom.HtmlAttribute>(((haxe.ds.StringMap<ub1.server.dom.HtmlAttribute>) (((haxe.IMap<java.lang.String, ub1.server.dom.HtmlAttribute>) (((ub1.server.dom.HtmlElement) (haxe.lang.Runtime.getField(def, "e", true)) ).attributes) )) ))) );
				//line 218 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(a, "hasNext", null)) )))
				{
					//line 218 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					ub1.server.dom.HtmlAttribute a1 = ((ub1.server.dom.HtmlAttribute) (haxe.lang.Runtime.callField(a, "next", null)) );
					//line 219 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					ret.setAttribute(a1.name, a1.value, a1.quote, a1.i1, a1.i2, a1.origin);
				}
				
			}
			
			//line 221 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			ub1.lib.DomTools.domSetHtml(ret, ((ub1.server.dom.HtmlElement) (haxe.lang.Runtime.getField(def, "e", true)) ).getInnerHTML());
		}
		
		//line 223 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		this.populateMacro(use, ret);
		//line 224 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		return ret;
	}
	
	
	public void populateMacro(ub1.server.dom.HtmlElement src, ub1.server.dom.HtmlElement dst)
	{
		//line 228 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 228 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			java.lang.Object a = ((java.lang.Object) (new haxe.ds._StringMap.StringMapValueIterator<ub1.server.dom.HtmlAttribute>(((haxe.ds.StringMap<ub1.server.dom.HtmlAttribute>) (((haxe.IMap<java.lang.String, ub1.server.dom.HtmlAttribute>) (src.attributes) )) ))) );
			//line 228 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(a, "hasNext", null)) )))
			{
				//line 228 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				ub1.server.dom.HtmlAttribute a1 = ((ub1.server.dom.HtmlAttribute) (haxe.lang.Runtime.callField(a, "next", null)) );
				//line 229 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				dst.setAttribute(a1.name, a1.value, a1.quote, a1.i1, a1.i2, a1.origin);
			}
			
		}
		
		//line 231 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.ds.StringMap<ub1.server.dom.HtmlElement> slots = this.collectSlots(dst);
		//line 232 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 232 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			int _g = 0;
			//line 232 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			haxe.root.Array<ub1.server.dom.HtmlNode> _g1 = src.children.copy();
			//line 232 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			while (( _g < _g1.length ))
			{
				//line 232 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				ub1.server.dom.HtmlNode n = _g1.__get(_g);
				//line 232 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				 ++ _g;
				//line 233 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.String slotName = "default";
				//line 233 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.String s = null;
				//line 234 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				boolean tmp = false;
				//line 234 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				if (( n.type == 1 )) 
				{
					//line 235 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					s = ub1.lib.DomTools.domGet(((ub1.server.dom.HtmlElement) (n) ), ":slot");
					//line 234 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					tmp = ( s != null );
				}
				else
				{
					//line 234 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					tmp = false;
				}
				
				//line 234 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				if (tmp) 
				{
					//line 236 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					slotName = s;
				}
				
				//line 238 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				ub1.server.dom.HtmlElement slot = ((ub1.server.dom.HtmlElement) (slots.get(slotName)) );
				//line 239 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				if (( slot == null )) 
				{
					//line 240 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					ub1.server.HtmlException err = new ub1.server.HtmlException(this.parser.origins.__get(n.origin), null, n.i1, this.sources.__get(n.origin));
					//line 243 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
					throw ((java.lang.RuntimeException) (haxe.Exception.thrown(new ub1.server.PreprocessorError(( ( "unknown slot \"" + slotName ) + "\"" ), err.fname, this.rootPath, err.row, err.col))) );
				}
				
				//line 247 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				slot.parent.addChild(n, slot);
			}
			
		}
		
		//line 249 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 249 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			java.lang.Object name = ((java.lang.Object) (new haxe.ds._StringMap.StringMapKeyIterator<ub1.server.dom.HtmlElement>(((haxe.ds.StringMap<ub1.server.dom.HtmlElement>) (slots) ))) );
			//line 249 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(name, "hasNext", null)) )))
			{
				//line 249 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				java.lang.String name1 = haxe.lang.Runtime.toString(haxe.lang.Runtime.callField(name, "next", null));
				//line 250 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				((ub1.server.dom.HtmlElement) (slots.get(name1)) ).remove();
			}
			
		}
		
	}
	
	
	public haxe.root.Array<ub1.server.dom.HtmlElement> lookupTags(ub1.server.dom.HtmlElement p, haxe.ds.StringMap<java.lang.Object> tags)
	{
		//line 259 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.root.Array<ub1.server.dom.HtmlElement> ret = new haxe.root.Array<ub1.server.dom.HtmlElement>();
		//line 260 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		haxe.lang.Function[] f = new haxe.lang.Function[]{null};
		//line 261 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		f[0] = new ub1.server.Preprocessor_lookupTags_261__Fun(tags, ret, f);
		//line 272 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		f[0].__hx_invoke1_o(0.0, p);
		//line 273 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		return ret;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case -1081745881:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("macros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.macros = ((haxe.ds.StringMap<java.lang.Object>) (value) );
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -166979545:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("rootPath")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.rootPath = haxe.lang.Runtime.toString(value);
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -2021876808:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("sources")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.sources = ((haxe.root.Array<java.lang.String>) (value) );
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -995410913:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("parser")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.parser = ((ub1.server.HtmlParser) (value) );
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case 1300104371:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("lookupTags")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "lookupTags")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -166979545:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("rootPath")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.rootPath;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 188761346:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("populateMacro")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "populateMacro")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -995410913:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("parser")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.parser;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -454632110:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("expandMacro")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "expandMacro")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -2021876808:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("sources")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.sources;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -1208693407:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("expandMacros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "expandMacros")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -1081745881:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("macros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.macros;
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1615671083:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("collectSlots")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "collectSlots")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 3496342:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("read")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "read")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1609790658:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("collectMacro")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "collectMacro")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -867956686:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("readFile")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "readFile")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -1636097039:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("collectMacros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "collectMacros")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1752622170:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("processIncludes")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "processIncludes")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1132271990:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("processMacros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "processMacros")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1857651513:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("processInclude")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "processInclude")) );
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case 1300104371:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("lookupTags")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.lookupTags(((ub1.server.dom.HtmlElement) (dynargs[0]) ), ((haxe.ds.StringMap<java.lang.Object>) (dynargs[1]) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 3496342:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("read")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.read(haxe.lang.Runtime.toString(dynargs[0]));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 188761346:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("populateMacro")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.populateMacro(((ub1.server.dom.HtmlElement) (dynargs[0]) ), ((ub1.server.dom.HtmlElement) (dynargs[1]) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -867956686:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("readFile")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.readFile(haxe.lang.Runtime.toString(dynargs[0]), haxe.lang.Runtime.toString(( (( dynargs.length > 1 )) ? (dynargs[1]) : (null) )), ( (( dynargs.length > 2 )) ? (dynargs[2]) : (null) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -454632110:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("expandMacro")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.expandMacro(((ub1.server.dom.HtmlElement) (dynargs[0]) ), dynargs[1]);
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1752622170:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("processIncludes")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.processIncludes(((ub1.server.dom.HtmlDocument) (dynargs[0]) ), haxe.lang.Runtime.toString(dynargs[1]));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -1208693407:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("expandMacros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.expandMacros(((ub1.server.dom.HtmlElement) (dynargs[0]) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1857651513:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("processInclude")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.processInclude(((ub1.server.dom.HtmlElement) (dynargs[0]) ), haxe.lang.Runtime.toString(dynargs[1]), haxe.lang.Runtime.toBool(((java.lang.Boolean) (dynargs[2]) )), haxe.lang.Runtime.toString(dynargs[3]));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1615671083:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("collectSlots")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.collectSlots(((ub1.server.dom.HtmlElement) (dynargs[0]) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1132271990:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("processMacros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.processMacros(((ub1.server.dom.HtmlDocument) (dynargs[0]) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 1609790658:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("collectMacro")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.collectMacro(((ub1.server.dom.HtmlElement) (dynargs[0]) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case -1636097039:
					{
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("collectMacros")) 
						{
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.collectMacros(((ub1.server.dom.HtmlElement) (dynargs[0]) ));
						}
						
						//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("macros");
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("sources");
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("parser");
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("rootPath");
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


