// Generated by Haxe 4.1.5
package ub1.server;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class PreprocessorError extends haxe.lang.HxObject
{
	public PreprocessorError(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public PreprocessorError(java.lang.String msg, java.lang.String fname, java.lang.String rootPath, java.lang.Object row, java.lang.Object col)
	{
		//line 284 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		ub1.server.PreprocessorError.__hx_ctor_ub1_server_PreprocessorError(this, msg, fname, rootPath, row, col);
	}
	
	
	protected static void __hx_ctor_ub1_server_PreprocessorError(ub1.server.PreprocessorError __hx_this, java.lang.String msg, java.lang.String fname, java.lang.String rootPath, java.lang.Object row, java.lang.Object col)
	{
		//line 285 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.msg = msg;
		//line 286 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.fname = ( (( ( ( rootPath != null ) && ( fname != null ) ) && ((java.lang.String) (((java.lang.Object) (fname) )) ).startsWith(haxe.lang.Runtime.toString(rootPath)) )) ? (haxe.lang.StringExt.substr(fname, rootPath.length(), null)) : (fname) );
		//line 289 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.row = ((int) (haxe.lang.Runtime.toInt(row)) );
		//line 290 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		__hx_this.col = ((int) (haxe.lang.Runtime.toInt(col)) );
	}
	
	
	public java.lang.String msg;
	
	public java.lang.String fname;
	
	public int row;
	
	public int col;
	
	@Override public java.lang.String toString()
	{
		//line 294 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		if (( this.fname != null )) 
		{
			//line 294 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			return ( ( ( ( ( ( ( "" + this.fname ) + ":" ) + this.row ) + " col " ) + this.col ) + ": " ) + this.msg );
		}
		else
		{
			//line 294 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			return this.msg;
		}
		
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case 98688:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("col")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.col = ((int) (value) );
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 113114:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("row")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.row = ((int) (value) );
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_setField_f(field, value, handleProperties);
			}
			else
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case 98688:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("col")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.col = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 108417:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("msg")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.msg = haxe.lang.Runtime.toString(value);
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 113114:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("row")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.row = ((int) (haxe.lang.Runtime.toInt(value)) );
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 97572849:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("fname")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							this.fname = haxe.lang.Runtime.toString(value);
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return value;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case -1776922004:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("toString")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "toString")) );
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 108417:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("msg")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.msg;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 98688:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("col")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.col;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 97572849:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("fname")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.fname;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 113114:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("row")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.row;
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case 98688:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("col")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((double) (this.col) );
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
					case 113114:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("row")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return ((double) (this.row) );
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_getField_f(field, throwErrors, handleProperties);
			}
			else
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		{
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			boolean __temp_executeDef1 = true;
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (( field != null )) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				switch (field.hashCode())
				{
					case -1776922004:
					{
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						if (field.equals("toString")) 
						{
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							__temp_executeDef1 = false;
							//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
							return this.toString();
						}
						
						//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
			if (__temp_executeDef1) 
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("col");
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("row");
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("fname");
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		baseArr.push("msg");
		//line 278 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/server/Preprocessor.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


