// Generated by Haxe 4.1.5
package ub1.lib;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class ArrayTools_arraySort_18__Fun extends haxe.lang.Function
{
	public ArrayTools_arraySort_18__Fun()
	{
		//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
		super(2, 1);
	}
	
	
	public static ub1.lib.ArrayTools_arraySort_18__Fun __hx_current;
	
	@Override public double __hx_invoke2_f(double __fn_float1, java.lang.Object __fn_dyn1, double __fn_float2, java.lang.Object __fn_dyn2)
	{
		//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
		java.lang.String b = ( (( __fn_dyn2 == haxe.lang.Runtime.undefined )) ? (haxe.lang.Runtime.toString(__fn_float2)) : (haxe.lang.Runtime.toString(__fn_dyn2)) );
		//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
		java.lang.String a = ( (( __fn_dyn1 == haxe.lang.Runtime.undefined )) ? (haxe.lang.Runtime.toString(__fn_float1)) : (haxe.lang.Runtime.toString(__fn_dyn1)) );
		//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
		if (( a.compareTo(b) > 0 )) 
		{
			//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
			return ((double) (1) );
		}
		else
		{
			//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
			if (( a.compareTo(b) < 0 )) 
			{
				//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
				return ((double) (-1) );
			}
			else
			{
				//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/ArrayTools.hx"
				return ((double) (0) );
			}
			
		}
		
	}
	
	
}


