// Generated by Haxe 4.1.5
package ub1.lib;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class BaseNode extends haxe.lang.HxObject
{
	static
	{
		//line 4 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode.SELF_SLOT = "self";
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode.DEFAULT_SLOT = "default";
		//line 6 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode.CATCHALL_SLOT = "catchall";
		//line 145 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode.NOCHILDREN = new haxe.root.Array<ub1.lib.BaseNode>(new ub1.lib.BaseNode[]{});
	}
	
	public BaseNode(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public BaseNode(ub1.lib.BaseNode parent, java.lang.String plug, java.lang.Object index, haxe.lang.Function cb)
	{
		//line 17 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode.__hx_ctor_ub1_lib_BaseNode(this, parent, plug, index, cb);
	}
	
	
	protected static void __hx_ctor_ub1_lib_BaseNode(ub1.lib.BaseNode __hx_this, ub1.lib.BaseNode parent, java.lang.String plug, java.lang.Object index, haxe.lang.Function cb)
	{
		//line 18 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		__hx_this.baseRoot = ( (( (__hx_this.baseParent = parent) != null )) ? (parent.baseRoot) : (__hx_this) );
		//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		__hx_this.init();
		//line 20 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( parent != null )) 
		{
			//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			parent.addChild(__hx_this, plug, index);
		}
		
		//line 23 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( cb != null )) 
		{
			//line 23 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			((haxe.lang.Function) (cb) ).__hx_invoke1_o(0.0, __hx_this);
		}
		
	}
	
	
	public static java.lang.String SELF_SLOT;
	
	public static java.lang.String DEFAULT_SLOT;
	
	public static java.lang.String CATCHALL_SLOT;
	
	public static haxe.root.Array<ub1.lib.BaseNode> NOCHILDREN;
	
	public ub1.lib.BaseNode logicalParent;
	
	public ub1.lib.BaseNode baseParent;
	
	public haxe.root.Array<ub1.lib.BaseNode> baseChildren;
	
	public haxe.root.Array<ub1.lib.BaseNode> get_baseChildren()
	{
		//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( this._cdn != null )) 
		{
			//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			return this._cdn;
		}
		else
		{
			//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			return ub1.lib.BaseNode.NOCHILDREN;
		}
		
	}
	
	
	public ub1.lib.BaseNode before;
	
	public ub1.lib.BaseNode getSlot(java.lang.String name, haxe.lang.Function cb)
	{
		//line 27 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode ret = null;
		//line 34 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( haxe.lang.Runtime.valEq(name, "self") || ( this.slots == null ) )) 
		{
			//line 35 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			ret = this;
		}
		else
		{
			//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( name == null )) 
			{
				//line 37 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				name = "default";
			}
			
			//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			ret = ((ub1.lib.BaseNode) (((haxe.ds.StringMap<ub1.lib.BaseNode>) (((haxe.IMap<java.lang.String, ub1.lib.BaseNode>) (this.slots) )) ).get(name)) );
			//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( ret == null )) 
			{
				//line 39 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				ret = ((ub1.lib.BaseNode) (((haxe.ds.StringMap<ub1.lib.BaseNode>) (((haxe.IMap<java.lang.String, ub1.lib.BaseNode>) (this.slots) )) ).get("catchall")) );
			}
			
		}
		
		//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( ret == null )) 
		{
			//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			ret = this;
		}
		
		//line 44 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( cb != null )) 
		{
			//line 44 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			((haxe.lang.Function) (cb) ).__hx_invoke1_o(0.0, ret);
		}
		
		//line 45 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return ret;
	}
	
	
	public ub1.lib.BaseNode addChild(ub1.lib.BaseNode child, java.lang.String plug, java.lang.Object before)
	{
		//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode p = this.getSlot(plug, null);
		//line 50 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( p != null )) 
		{
			//line 51 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( p._cdn == null )) 
			{
				//line 52 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				p._cdn = new haxe.root.Array<ub1.lib.BaseNode>(new ub1.lib.BaseNode[]{});
			}
			
			//line 54 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			int i = 0;
			//line 54 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			java.lang.Object pos = ( (( ! (haxe.lang.Runtime.eq(before, null)) )) ? (before) : (p._cdn.length) );
			//line 55 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( this.before != null )) 
			{
				//line 56 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				i = this.before.getIndex();
				//line 56 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				if (( i >= 0 )) 
				{
					//line 57 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
					if (( i < ((int) (haxe.lang.Runtime.toInt(pos)) ) )) 
					{
						//line 57 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						pos = i;
					}
					
				}
				
			}
			
			//line 60 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			p._cdn.insert(((int) (haxe.lang.Runtime.toInt(pos)) ), child);
			//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( ((int) (haxe.lang.Runtime.toInt(pos)) ) >= 0 )) 
			{
				//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				int __temp_expr1 = ((int) (haxe.lang.Runtime.toInt(pos = ( ((int) (haxe.lang.Runtime.toInt(pos)) ) + 1 ))) );
			}
			
			//line 62 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			child.logicalParent = this;
			//line 63 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			child.baseParent = p;
			//line 64 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			child.wasAdded(this, p, pos);
		}
		
		//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return this;
	}
	
	
	public final void remove()
	{
		//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( this.baseParent != null )) 
		{
			//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			this.baseParent.removeChild(this);
		}
		
	}
	
	
	public ub1.lib.BaseNode removeChild(ub1.lib.BaseNode child)
	{
		//line 74 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( ( this._cdn != null ) && this._cdn.remove(child) )) 
		{
			//line 75 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			ub1.lib.BaseNode logicalParent = child.logicalParent;
			//line 76 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			child.logicalParent = null;
			//line 77 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			child.baseParent = null;
			//line 78 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			child.wasRemoved(logicalParent, this);
		}
		
		//line 80 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return child;
	}
	
	
	public ub1.lib.BaseNode removeChildren()
	{
		//line 84 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		while (( ( this._cdn != null ) && ( this._cdn.length > 0 ) ))
		{
			//line 85 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			this.removeChild(this._cdn.__get(( this._cdn.length - 1 )));
		}
		
		//line 87 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return this;
	}
	
	
	public final boolean hasChildren()
	{
		//line 91 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( this._cdn != null )) 
		{
			//line 91 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			return ( this._cdn.length > 0 );
		}
		else
		{
			//line 91 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			return false;
		}
		
	}
	
	
	public ub1.lib.BaseNode getPrevSibling()
	{
		//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode ret = null;
		//line 103 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( this.baseParent != null )) 
		{
			//line 104 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			int i = this.baseParent.get_baseChildren().indexOf(this, null);
			//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( i > 0 )) 
			{
				//line 105 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				ret = this.baseParent.get_baseChildren().__get(( i - 1 ));
			}
			
		}
		
		//line 107 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return ret;
	}
	
	
	public ub1.lib.BaseNode getNextSibling()
	{
		//line 111 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		ub1.lib.BaseNode ret = null;
		//line 112 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( this.baseParent != null )) 
		{
			//line 113 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			int len = this.baseParent.get_baseChildren().length;
			//line 114 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			int i = this.baseParent.get_baseChildren().indexOf(this, null);
			//line 115 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( ( i >= 0 ) && ( i < ( len - 1 ) ) )) 
			{
				//line 115 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				ret = this.baseParent.get_baseChildren().__get(( i + 1 ));
			}
			
		}
		
		//line 116 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return ret;
	}
	
	
	public int getIndex()
	{
		//line 120 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		int ret = ( (( this.baseParent != null )) ? (this.baseParent.get_baseChildren().indexOf(this, null)) : (-1) );
		//line 121 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return ret;
	}
	
	
	public void assertEquals(ub1.lib.BaseNode bn, java.lang.String msg)
	{
		//line 126 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( this.get_baseChildren().length != bn.get_baseChildren().length )) 
		{
			//line 127 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			haxe.Log.trace.__hx_invoke2_o(0.0, "", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"ub1.lib.BaseNode", "../ub1-core/src/ub1/lib/BaseNode.hx", "assertEquals"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (127) )) )}));
		}
		
		//line 129 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		utest.Assert.equals(this.get_baseChildren().length, bn.get_baseChildren().length, ( ( ( ( "BaseNode.hx: " + msg ) + ": different child count" ) + (( ( " " + this.get_baseChildren().length ) + " !=" )) ) + (( " " + bn.get_baseChildren().length )) ), new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"ub1.lib.BaseNode", "../ub1-core/src/ub1/lib/BaseNode.hx", "assertEquals"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (129) )) )}));
		//line 134 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		if (( this.get_baseChildren().length == bn.get_baseChildren().length )) 
		{
			//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			int _g = 0;
			//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			int _g1 = ub1.lib.ArrayTools.arrayLength(((haxe.root.Array) (this.get_baseChildren()) ));
			//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			while (( _g < _g1 ))
			{
				//line 135 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				int i = _g++;
				//line 136 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				this.get_baseChildren().__get(i).assertEquals(bn.get_baseChildren().__get(i), null);
			}
			
		}
		
	}
	
	
	public haxe.root.Array<ub1.lib.BaseNode> _cdn;
	
	public ub1.lib.BaseNode baseRoot;
	
	public haxe.ds.StringMap<ub1.lib.BaseNode> slots;
	
	public void init()
	{
	}
	
	
	public void wasAdded(ub1.lib.BaseNode logicalParent, ub1.lib.BaseNode parent, java.lang.Object before)
	{
	}
	
	
	public void wasRemoved(ub1.lib.BaseNode logicalParent, ub1.lib.BaseNode parent)
	{
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				switch (field.hashCode())
				{
					case 109532725:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("slots")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.slots = ((haxe.ds.StringMap<ub1.lib.BaseNode>) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1586846189:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("logicalParent")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.logicalParent = ((ub1.lib.BaseNode) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1721554093:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("baseRoot")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.baseRoot = ((ub1.lib.BaseNode) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -921183525:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("baseParent")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.baseParent = ((ub1.lib.BaseNode) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 2928494:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("_cdn")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this._cdn = ((haxe.root.Array<ub1.lib.BaseNode>) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -9738256:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("baseChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.baseChildren = ((haxe.root.Array<ub1.lib.BaseNode>) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1392885889:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("before")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.before = ((ub1.lib.BaseNode) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				switch (field.hashCode())
				{
					case 176520503:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("wasRemoved")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "wasRemoved")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1586846189:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("logicalParent")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.logicalParent;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 485003159:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("wasAdded")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "wasAdded")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -921183525:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("baseParent")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.baseParent;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 3237136:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("init")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "init")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -9738256:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("baseChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ( (handleProperties) ? (this.get_baseChildren()) : (this.baseChildren) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 109532725:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("slots")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.slots;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 264986169:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("get_baseChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "get_baseChildren")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1721554093:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("baseRoot")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.baseRoot;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1392885889:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("before")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.before;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 2928494:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("_cdn")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this._cdn;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -75148684:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getSlot")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getSlot")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1076899163:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("assertEquals")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "assertEquals")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1262040837:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("addChild")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "addChild")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 1956171548:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getIndex")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getIndex")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -934610812:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("remove")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "remove")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1499802855:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getNextSibling")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getNextSibling")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -319766792:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("removeChild")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "removeChild")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 114103257:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getPrevSibling")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "getPrevSibling")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 65074851:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("removeChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "removeChildren")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 239016633:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("hasChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "hasChildren")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				switch (field.hashCode())
				{
					case 176520503:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("wasRemoved")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.wasRemoved(((ub1.lib.BaseNode) (dynargs[0]) ), ((ub1.lib.BaseNode) (dynargs[1]) ));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 264986169:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("get_baseChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.get_baseChildren();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 485003159:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("wasAdded")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.wasAdded(((ub1.lib.BaseNode) (dynargs[0]) ), ((ub1.lib.BaseNode) (dynargs[1]) ), ( (( dynargs.length > 2 )) ? (dynargs[2]) : (null) ));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -75148684:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getSlot")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.getSlot(haxe.lang.Runtime.toString(dynargs[0]), ((haxe.lang.Function) (( (( dynargs.length > 1 )) ? (dynargs[1]) : (null) )) ));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 3237136:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("init")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.init();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1262040837:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("addChild")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.addChild(((ub1.lib.BaseNode) (dynargs[0]) ), haxe.lang.Runtime.toString(( (( dynargs.length > 1 )) ? (dynargs[1]) : (null) )), ( (( dynargs.length > 2 )) ? (dynargs[2]) : (null) ));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1076899163:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("assertEquals")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.assertEquals(((ub1.lib.BaseNode) (dynargs[0]) ), haxe.lang.Runtime.toString(( (( dynargs.length > 1 )) ? (dynargs[1]) : (null) )));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -934610812:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("remove")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							this.remove();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 1956171548:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getIndex")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.getIndex();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -319766792:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("removeChild")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.removeChild(((ub1.lib.BaseNode) (dynargs[0]) ));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case -1499802855:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getNextSibling")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.getNextSibling();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 65074851:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("removeChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.removeChildren();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 114103257:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("getPrevSibling")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.getPrevSibling();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
					case 239016633:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						if (field.equals("hasChildren")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
							return this.hasChildren();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		baseArr.push("slots");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		baseArr.push("baseRoot");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		baseArr.push("_cdn");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		baseArr.push("before");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		baseArr.push("baseChildren");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		baseArr.push("baseParent");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		baseArr.push("logicalParent");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/BaseNode.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


