// Generated by Haxe 4.1.5
package ub1.lib;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class DoubleLinkedItem extends haxe.lang.HxObject
{
	public DoubleLinkedItem(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public DoubleLinkedItem()
	{
		//line 7 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		ub1.lib.DoubleLinkedItem.__hx_ctor_ub1_lib_DoubleLinkedItem(this);
	}
	
	
	protected static void __hx_ctor_ub1_lib_DoubleLinkedItem(ub1.lib.DoubleLinkedItem __hx_this)
	{
	}
	
	
	public ub1.lib.DoubleLinkedItem prev;
	
	public ub1.lib.DoubleLinkedItem next;
	
	public ub1.lib.DoubleLinkedItem linkAfter(ub1.lib.DoubleLinkedItem other)
	{
		//line 10 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		this.prev = other;
		//line 11 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		if (( (this.next = other.next) != null )) 
		{
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			this.next.prev = this;
		}
		
		//line 14 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		other.next = this;
		//line 15 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		return this;
	}
	
	
	public ub1.lib.DoubleLinkedItem unlink()
	{
		//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		if (( this.prev != null )) 
		{
			//line 20 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			this.prev.next = this.next;
		}
		
		//line 22 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		if (( this.next != null )) 
		{
			//line 23 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			this.next.prev = this.prev;
		}
		
		//line 25 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		return this;
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				switch (field.hashCode())
				{
					case 3377907:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("next")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							this.next = ((ub1.lib.DoubleLinkedItem) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
					case 3449395:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("prev")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							this.prev = ((ub1.lib.DoubleLinkedItem) (value) );
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return value;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				switch (field.hashCode())
				{
					case -840447469:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("unlink")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "unlink")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
					case 3449395:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("prev")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return this.prev;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
					case -1652403710:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("linkAfter")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "linkAfter")) );
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
					case 3377907:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("next")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return this.next;
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		{
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			boolean __temp_executeDef1 = true;
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			if (( field != null )) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				switch (field.hashCode())
				{
					case -840447469:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("unlink")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return this.unlink();
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
					case -1652403710:
					{
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						if (field.equals("linkAfter")) 
						{
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							__temp_executeDef1 = false;
							//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
							return this.linkAfter(((ub1.lib.DoubleLinkedItem) (dynargs[0]) ));
						}
						
						//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
			if (__temp_executeDef1) 
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			else
			{
				//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		baseArr.push("next");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		baseArr.push("prev");
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/DoubleLinkedItem.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


