// Generated by Haxe 4.1.5
package ub1.lib;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class MapTools extends haxe.lang.HxObject
{
	public MapTools(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public MapTools()
	{
		//line 3 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		ub1.lib.MapTools.__hx_ctor_ub1_lib_MapTools(this);
	}
	
	
	protected static void __hx_ctor_ub1_lib_MapTools(ub1.lib.MapTools __hx_this)
	{
	}
	
	
	public static void mapCopy(haxe.ds.StringMap<java.lang.Object> src, haxe.ds.StringMap<java.lang.Object> dst)
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		java.lang.Object key = ((java.lang.Object) (new haxe.ds._StringMap.StringMapKeyIterator(((haxe.ds.StringMap<java.lang.Object>) (src) ))) );
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(key, "hasNext", null)) )))
		{
			//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			java.lang.String key1 = haxe.lang.Runtime.toString(haxe.lang.Runtime.callField(key, "next", null));
			//line 6 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			dst.set(key1, ((java.lang.Object) (src.get(key1)) ));
		}
		
	}
	
	
	public static boolean mapIsEmpty(haxe.ds.StringMap<java.lang.Object> map)
	{
		//line 11 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		if (( map != null )) 
		{
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			java.lang.Object key = ((java.lang.Object) (new haxe.ds._StringMap.StringMapKeyIterator(((haxe.ds.StringMap<java.lang.Object>) (map) ))) );
			//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(key, "hasNext", null)) )))
			{
				//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				java.lang.String key1 = haxe.lang.Runtime.toString(haxe.lang.Runtime.callField(key, "next", null));
				//line 13 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				return false;
			}
			
		}
		
		//line 16 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		return true;
	}
	
	
	public static boolean mapRemoveObject(haxe.IMap map, java.lang.Object obj)
	{
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		boolean ret = false;
		//line 21 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		java.lang.Object key = null;
		//line 22 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		while (true)
		{
			//line 22 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			key = ub1.lib.MapTools.mapKeyOf(map, obj);
			//line 22 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			if ( ! ((( ! (( key == null )) ))) ) 
			{
				//line 22 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				break;
			}
			
			//line 23 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			map.remove(key);
			//line 24 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			ret = true;
		}
		
		//line 26 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		return ret;
	}
	
	
	public static java.lang.Object mapKeyOf(haxe.IMap map, java.lang.Object obj)
	{
		//line 31 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		if (( map != null )) 
		{
			//line 32 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			java.lang.Object key = map.keys();
			//line 32 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(key, "hasNext", null)) )))
			{
				//line 32 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				java.lang.Object key1 = ((java.lang.Object) (haxe.lang.Runtime.callField(key, "next", null)) );
				//line 33 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				if (haxe.lang.Runtime.eq(map.get(key1), obj)) 
				{
					//line 34 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
					return key1;
				}
				
			}
			
		}
		
		//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		return null;
	}
	
	
	public static boolean mapsAreEqual(haxe.ds.StringMap<java.lang.Object> a, haxe.ds.StringMap<java.lang.Object> b)
	{
		//line 42 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		if (( ( a == null ) && ( b == null ) )) 
		{
			//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			return true;
		}
		else
		{
			//line 44 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			if (( ( a == null ) || ( b == null ) )) 
			{
				//line 45 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				return false;
			}
			else
			{
				//line 46 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				if (( ub1.lib.MapTools.mapSize(a) != ub1.lib.MapTools.mapSize(b) )) 
				{
					//line 47 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
					return false;
				}
				else
				{
					//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
					java.lang.Object key = ((java.lang.Object) (new haxe.ds._StringMap.StringMapKeyIterator(((haxe.ds.StringMap<java.lang.Object>) (a) ))) );
					//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
					while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(key, "hasNext", null)) )))
					{
						//line 49 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
						java.lang.String key1 = haxe.lang.Runtime.toString(haxe.lang.Runtime.callField(key, "next", null));
						//line 50 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
						if (( ! (haxe.lang.Runtime.eq(((java.lang.Object) (a.get(key1)) ), ((java.lang.Object) (b.get(key1)) ))) )) 
						{
							//line 51 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
							return false;
						}
						
					}
					
				}
				
			}
			
		}
		
		//line 55 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		return true;
	}
	
	
	public static int mapSize(haxe.ds.StringMap<java.lang.Object> map)
	{
		//line 59 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		int ret = 0;
		//line 60 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		if (( map != null )) 
		{
			//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			java.lang.Object key = ((java.lang.Object) (new haxe.ds._StringMap.StringMapKeyIterator(((haxe.ds.StringMap<java.lang.Object>) (map) ))) );
			//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(key, "hasNext", null)) )))
			{
				//line 61 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				java.lang.String key1 = haxe.lang.Runtime.toString(haxe.lang.Runtime.callField(key, "next", null));
				//line 62 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				 ++ ret;
			}
			
		}
		
		//line 65 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		return ret;
	}
	
	
	public static void mapClear(haxe.IMap map, haxe.lang.Function cb)
	{
		//line 69 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		haxe.root.Array keys = new haxe.root.Array(new java.lang.Object[]{});
		//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		{
			//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			java.lang.Object key = map.keys();
			//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			while (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.callField(key, "hasNext", null)) )))
			{
				//line 70 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				java.lang.Object key1 = ((java.lang.Object) (haxe.lang.Runtime.callField(key, "next", null)) );
				//line 71 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				keys.push(key1);
			}
			
		}
		
		//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
		{
			//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			int _g = 0;
			//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
			while (( _g < keys.length ))
			{
				//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				java.lang.Object key2 = keys.__get(_g);
				//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				 ++ _g;
				//line 73 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				if (( cb != null )) 
				{
					//line 73 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
					((haxe.lang.Function) (cb) ).__hx_invoke2_o(0.0, key2, 0.0, map.get(key2));
				}
				
				//line 74 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/MapTools.hx"
				map.remove(key2);
			}
			
		}
		
	}
	
	
}


