// Generated by Haxe 4.1.5
package ub1.lib;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class PropertyTools extends haxe.lang.HxObject
{
	public PropertyTools(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public PropertyTools()
	{
		//line 5 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		ub1.lib.PropertyTools.__hx_ctor_ub1_lib_PropertyTools(this);
	}
	
	
	protected static void __hx_ctor_ub1_lib_PropertyTools(ub1.lib.PropertyTools __hx_this)
	{
	}
	
	
	public static java.lang.Object get(java.lang.Object props, java.lang.String key, java.lang.Object defval)
	{
		//line 7 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		java.lang.Object val = ( (( ! (( props == null )) )) ? (haxe.root.Reflect.getProperty(props, key)) : (null) );
		//line 8 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( val == null )) )) 
		{
			//line 8 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return val;
		}
		else
		{
			//line 8 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return defval;
		}
		
	}
	
	
	public static java.lang.String getString(java.lang.Object props, java.lang.String key, java.lang.String defval)
	{
		//line 12 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return haxe.lang.Runtime.toString(ub1.lib.PropertyTools.get(props, key, defval));
	}
	
	
	public static int getInt(java.lang.Object props, java.lang.String key, java.lang.Object defval)
	{
		//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		int defval1 = ( (haxe.lang.Runtime.eq(defval, null)) ? (0) : (((int) (haxe.lang.Runtime.toInt(defval)) )) );
		//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		java.lang.Object ret = haxe.root.Std.parseInt(haxe.lang.Runtime.toString(ub1.lib.PropertyTools.get(props, key, null)));
		//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (haxe.lang.Runtime.eq(ret, null)) )) 
		{
			//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return ((int) (haxe.lang.Runtime.toInt(ret)) );
		}
		else
		{
			//line 19 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return defval1;
		}
		
	}
	
	
	public static java.lang.Object set(java.lang.Object props, java.lang.String key, java.lang.Object val)
	{
		//line 23 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( val == null )) )) 
		{
			//line 24 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			if (( props == null )) 
			{
				//line 25 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				props = new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{});
			}
			
			//line 27 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			haxe.root.Reflect.setProperty(props, key, val);
		}
		else
		{
			//line 28 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			if (( ! (( props == null )) )) 
			{
				//line 29 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				haxe.root.Reflect.deleteField(props, key);
			}
			
		}
		
		//line 31 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return props;
	}
	
	
	public static java.lang.Object set2(java.lang.Object props, java.lang.String key, java.lang.Object val)
	{
		//line 35 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( props == null )) 
		{
			//line 36 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			props = new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{});
		}
		
		//line 38 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		haxe.root.Reflect.setProperty(props, key, val);
		//line 39 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return props;
	}
	
	
	public static boolean exists(java.lang.Object props, java.lang.String key)
	{
		//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( props == null )) )) 
		{
			//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return haxe.root.Reflect.hasField(props, key);
		}
		else
		{
			//line 43 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return false;
		}
		
	}
	
	
	public static void remove(java.lang.Object props, java.lang.String key)
	{
		//line 47 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( props == null )) )) 
		{
			//line 48 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			haxe.root.Reflect.deleteField(props, key);
		}
		
	}
	
	
	public static haxe.root.Array<java.lang.String> keys(java.lang.Object props)
	{
		//line 53 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( props == null )) )) 
		{
			//line 53 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return haxe.root.Reflect.fields(props);
		}
		else
		{
			//line 53 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			return new haxe.root.Array<java.lang.String>(new java.lang.String[]{});
		}
		
	}
	
	
	public static java.lang.Object ensure(java.lang.Object props, java.lang.String key, java.lang.Object val)
	{
		//line 57 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if ( ! (ub1.lib.PropertyTools.exists(props, key)) ) 
		{
			//line 58 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			props = ub1.lib.PropertyTools.set(props, key, val);
		}
		
		//line 60 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return props;
	}
	
	
	public static java.lang.Object ensure2(java.lang.Object props, java.lang.String key, java.lang.Object val)
	{
		//line 64 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( props == null )) 
		{
			//line 64 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			props = new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{});
		}
		
		//line 65 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if ( ! (ub1.lib.PropertyTools.exists(props, key)) ) 
		{
			//line 66 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			ub1.lib.PropertyTools.set2(props, key, val);
		}
		
		//line 68 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return props;
	}
	
	
	public static java.lang.Object ensureWith(java.lang.Object props, java.lang.Object with)
	{
		//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		{
			//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			int _g = 0;
			//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			haxe.root.Array<java.lang.String> _g1 = ( (( ! (( with == null )) )) ? (haxe.root.Reflect.fields(with)) : (new haxe.root.Array<java.lang.String>(new java.lang.String[]{})) );
			//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			while (( _g < _g1.length ))
			{
				//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				java.lang.String key = _g1.__get(_g);
				//line 72 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				 ++ _g;
				//line 73 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				props = ub1.lib.PropertyTools.ensure(props, key, ub1.lib.PropertyTools.get(with, key, null));
			}
			
		}
		
		//line 75 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return props;
	}
	
	
	public static java.lang.Object clone(java.lang.Object props)
	{
		//line 79 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		java.lang.Object ret = null;
		//line 80 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( props == null )) )) 
		{
			//line 81 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			ret = new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{});
			//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			{
				//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				int _g = 0;
				//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				haxe.root.Array<java.lang.String> _g1 = ( (( ! (( props == null )) )) ? (haxe.root.Reflect.fields(props)) : (new haxe.root.Array<java.lang.String>(new java.lang.String[]{})) );
				//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				while (( _g < _g1.length ))
				{
					//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
					java.lang.String key = _g1.__get(_g);
					//line 82 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
					 ++ _g;
					//line 83 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
					ub1.lib.PropertyTools.set(ret, key, ub1.lib.PropertyTools.get(props, key, null));
				}
				
			}
			
		}
		
		//line 86 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return ret;
	}
	
	
	public static java.lang.Object overwriteWith(java.lang.Object props, java.lang.Object with)
	{
		//line 90 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		java.lang.Object ret = ( (( ! (( props == null )) )) ? (props) : (new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{})) );
		//line 91 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( with == null )) )) 
		{
			//line 92 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			int _g = 0;
			//line 92 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			haxe.root.Array<java.lang.String> _g1 = ( (( ! (( with == null )) )) ? (haxe.root.Reflect.fields(with)) : (new haxe.root.Array<java.lang.String>(new java.lang.String[]{})) );
			//line 92 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			while (( _g < _g1.length ))
			{
				//line 92 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				java.lang.String key = _g1.__get(_g);
				//line 92 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				 ++ _g;
				//line 93 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				ub1.lib.PropertyTools.set(ret, key, ub1.lib.PropertyTools.get(with, key, null));
			}
			
		}
		
		//line 96 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return ret;
	}
	
	
	public static java.lang.Object fillWith(java.lang.Object dst, java.lang.Object src, java.lang.Object overwrite)
	{
		//line 99 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		boolean overwrite1 = ( (haxe.lang.Runtime.eq(overwrite, null)) ? (false) : (haxe.lang.Runtime.toBool(((java.lang.Boolean) (overwrite) ))) );
		//line 100 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		java.lang.Object ret = ( (( ! (( dst == null )) )) ? (dst) : (new haxe.lang.DynamicObject(new java.lang.String[]{}, new java.lang.Object[]{}, new java.lang.String[]{}, new double[]{})) );
		//line 101 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( src == null )) )) 
		{
			//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			int _g = 0;
			//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			haxe.root.Array<java.lang.String> _g1 = ( (( ! (( src == null )) )) ? (haxe.root.Reflect.fields(src)) : (new haxe.root.Array<java.lang.String>(new java.lang.String[]{})) );
			//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			while (( _g < _g1.length ))
			{
				//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				java.lang.String key = _g1.__get(_g);
				//line 102 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				 ++ _g;
				//line 103 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				if (( overwrite1 ||  ! (ub1.lib.PropertyTools.exists(dst, key))  )) 
				{
					//line 104 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
					ub1.lib.PropertyTools.set(ret, key, ub1.lib.PropertyTools.get(src, key, null));
				}
				
			}
			
		}
		
		//line 108 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return ret;
	}
	
	
	public static java.lang.Object overwrite(java.lang.Object props, java.lang.String key, java.lang.Object val, java.lang.Object orRemove)
	{
		//line 111 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		boolean orRemove1 = ( (haxe.lang.Runtime.eq(orRemove, null)) ? (false) : (haxe.lang.Runtime.toBool(((java.lang.Boolean) (orRemove) ))) );
		//line 112 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		java.lang.Object ret = null;
		//line 112 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		{
			//line 113 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			boolean __temp_odecl1 = ub1.lib.PropertyTools.exists(props, key);
			//line 115 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			java.lang.Object __temp_odecl2 = ub1.lib.PropertyTools.get(props, key, null);
			//line 112 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			ret = new haxe.lang.DynamicObject(new java.lang.String[]{"existed", "key", "val"}, new java.lang.Object[]{__temp_odecl1, key, __temp_odecl2}, new java.lang.String[]{}, new double[]{});
		}
		
		//line 117 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (orRemove1) 
		{
			//line 117 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			ub1.lib.PropertyTools.remove(props, key);
		}
		else
		{
			//line 117 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			ub1.lib.PropertyTools.set(props, key, val);
		}
		
		//line 118 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		return ret;
	}
	
	
	public static void restore(java.lang.Object props, java.lang.Object old)
	{
		//line 122 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
		if (( ! (( old == null )) )) 
		{
			//line 123 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
			if (haxe.lang.Runtime.toBool(((java.lang.Boolean) (haxe.lang.Runtime.getField(old, "existed", true)) ))) 
			{
				//line 123 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				ub1.lib.PropertyTools.set(props, haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(old, "key", true)), haxe.lang.Runtime.getField(old, "val", true));
			}
			else
			{
				//line 123 "/Users/fabrizio/ubimate/oss/ub1/ub1-core/src/ub1/lib/PropertyTools.hx"
				ub1.lib.PropertyTools.remove(props, haxe.lang.Runtime.toString(haxe.lang.Runtime.getField(old, "key", true)));
			}
			
		}
		
	}
	
	
}


